;;; cli/clap/var.lisp --- Clap Variables

;; 

;;; Code:
(in-package :cli/clap)

(declaim (simple-string *cli-group-separator*))
(defparameter *no-exit* nil
  "Indicate whether the WITH-CLI-HANDLERS form should exit on completion.")

(defparameter *no-debug* nil
  "Indicate whether the WITH-CLI-HANDLERS form should enable the debugger.")

(defvar *default-cli-def* 'defparameter)

(defvar *default-cli-class* 'cli
  "The name of the class of the top-level CLI object which will be
generated by the DEFINE-CLI macro.")

(defvar *cli* nil
  "The current CLI object.
This symbol is bound in the body of the WITH-CLI macro.")

(defvar *cli-package-table* (make-hash-table)
  "A hash table containing a mapping of package names to CLI objects.")
