[package]
name = "nu_plugin_rocksdb"
version = "0.1.0"
edition = "2021"
description = "RocksDB for Nushell"
[[bin]]
name = "nu_plugin_alik"
path = "main.rs"
[dependencies]
nu-plugin = "0.89.0"
nu-protocol = { version = "0.89.0", features = ["plugin", "serde_json"] }
db = { path = "../../../lib/db" }