;;; Proto
(in-package :skel/core/proto)

(defgeneric sk-run (self)
  (:documentation "Run the object SELF."))
(defgeneric sk-new (self &rest args &key &allow-other-keys)
  (:documentation "Create a fresh instance of object SELF."))
(defgeneric sk-save (self)
  (:documentation "Save object SELF."))
(defgeneric sk-tangle (self &rest params &key &allow-other-keys)
  (:documentation "Tangle object self with params"))
(defgeneric sk-weave (self)
  (:documentation "Weave object self with params"))
(defgeneric sk-call (self arg)
  (:documentation "Call SELF with ARG."))
(defgeneric sk-call* (self &rest args)
  (:documentation "Call SELF with ARGS."))
(defgeneric sk-print (self)
  (:documentation "Print object SELF."))
(defgeneric sk-load (self &key &allow-other-keys)
  (:documentation "Load or reload object SELF."))
(defgeneric sk-load-component (kind form &optional path)
  (:documentation "Load a component of type KIND from provided FORM, producing an SK-COMPONENT
type. Usually calls SK-TRANSFORM or SK-CONVERT internally.

PATH is an optional directory pathname which will be merged with a filename found in FORM. Defaults to *DEFAULT-PATHNAME-DEFAULTS*."))
(defgeneric sk-compile (self &key &allow-other-keys)
  (:documentation "Compile object SELF."))
(defgeneric sk-build (self &key &allow-other-keys)
  (:documentation "Build a skel-object."))
(defgeneric sk-transform (self other &key &allow-other-keys)
  (:documentation "Transform SELF to skel-object of type OTHER."))
(defgeneric sk-convert (self)
  (:documentation "Convert the object SELF."))
(defgeneric sk-read (self stream)
  (:documentation "Read and fill SELF with an object from STREAM."))
(defgeneric sk-read-file (self path)
  (:documentation "Read a PATH from the filesystem with SELF."))
(defgeneric sk-write (self stream)
  (:documentation "Write object SELF to STREAM."))
(defgeneric sk-writeln (self stream)
  (:documentation "Write a line from SELF to STREAM."))
(defgeneric sk-write-string (self)
  (:documentation "Return a string from SELF."))
(defgeneric sk-write-file (self &key path &allow-other-keys)
  (:documentation "Write from SELF to file PATH."))
(defgeneric sk-install-user-config (self cfg)
  (:documentation "Populate SELF with configuration object CFG."))
(defgeneric sk-vc-push (self &key remote &allow-other-keys)
  (:documentation "Push object SELF upstream using vc."))
(defgeneric sk-vc-pull (self &key remote &allow-other-keys)
  (:documentation "Pull object SELF from upstream using vc."))
(defgeneric sk-find-rule (name self)
  (:documentation "Find a rule with the given NAME in SELF."))
(defgeneric sk-find-script (name self &key &allow-other-keys)
  (:documentation "Find a script with the given NAME in SELF."))
(defgeneric sk-find (item self &key &allow-other-keys))
(defgeneric sk-find* (items self &key &allow-other-keys))
(defgeneric sk-path (self)
  (:documentation "Return the canonical path to this object in the skel universe."))
(defgeneric sk-path-merge (self root)
  (:documentation "Merge path of SELF on ROOT."))
