;;; gstreamer.asd --- Gstreamer Sytem Definitions
(defsystem :gstreamer
  :depends-on (:std :log :glib)
  :components ((:file "pkg")
               (:file "object" :depends-on ("pkg"))
               (:file "clock" :depends-on ("object"))
               (:file "mini-object" :depends-on ("pkg"))
               (:file "caps" :depends-on ("mini-object"))
               (:file "context" :depends-on ("pkg"))
               (:file "task" :depends-on ("object"))
               (:file "iterator" :depends-on ("pkg"))
               (:file "message" :depends-on ("mini-object"))
               (:file "bus" :depends-on ("object" "message"))
               (:file "pad" :depends-on ("object"))
               (:file "element" :depends-on ("clock" "object" "iterator" "context"))
	       (:file "parse" :depends-on ("element"))
               (:file "element-factory" :depends-on ("element"))
               (:file "bin" :depends-on ("element"))
               (:file "pipeline" :depends-on ("bin"))
               (:file "debug" :depends-on ("bin"))
               (:file "play" :depends-on ("element" "bin"))
               (:file "ges" :depends-on ("element" "bin" "pipeline")))
  :in-order-to ((test-op (test-op "gstreamer/tests"))))

(defsystem :gstreamer/tests
  :depends-on (:std :log :rt :gstreamer :glib)
  :components ((:file "tests"))
  :perform (test-op (o c) (symbol-call :rt :do-tests :gstreamer)))
