;;; message.lisp --- GStreamer Message

;; 

;;; Code:
(in-package :gstreamer)

(define-alien-enum (gst-message-type int)
  :unknown 0
  :eos (ash 1 0)
  :error (ash 1 1)
  :warning (ash 1 2)
  :info (ash 1 3)
  :tag (ash 1 4)
  :buffering (ash 1 5)
  :state_changed (ash 1 6)
  :state_dirty (ash 1 7)
  :step_done (ash 1 8)
  :clock_provide (ash 1 9)
  :clock_lost (ash 1 10)
  :new_clock (ash 1 11)
  :structure_change (ash 1 12)
  :stream_status (ash 1 13)
  :application (ash 1 14)
  :element (ash 1 15)
  :segment_start (ash 1 16)
  :segment_done (ash 1 17)
  :duration_changed (ash 1 18)
  :latency (ash 1 19)
  :async_start (ash 1 20)
  :async_done (ash 1 21)
  :request_state (ash 1 22)
  :step_start (ash 1 23)
  :qos (ash 1 24)
  :progress (ash 1 25)
  :toc (ash 1 26)
  :reset_time (ash 1 27)
  :stream_start (ash 1 28)
  :need_context (ash 1 29)
  :have_context (ash 1 30)
  :extended (ash 1 31)
  :device_added (+ (ash 1 31) 1)
  :device_removed (+ (ash 1 31) 2)
  :property_notify (+ (ash 1 31) 3)
  :stream_collection (+ (ash 1 31) 4)
  :streams_selected (+ (ash 1 31) 5)
  :redirect (+ (ash 1 31) 6)
  :device_changed (+ (ash 1 31) 7)
  :instant_rate_request (+ (ash 1 31) 8)
  :any #xffffffff)

(define-alien-type gst-message
  (struct gst-message
    (mini-object gst-mini-object)
    (type gst-message-type)
    (timestamp unsigned-long)
    (src (* gst-object))
    (seqnum unsigned-int)
    (lock gmutex)
    (cond gcond)))

(defar gst-message-get-type gtype)
(defar gst-message-type-get-name c-string (type gst-message-type))
(defar gst-message-ref (* gst-message) (msg (* gst-message)))
(defar gst-message-unref void (msg (* gst-message)))
