("sys/types.h" "stdint.h" "keyutils.h")
( ;; ERROR_CODE
 (:integer +key-spec-thread-keyring+ "KEY_SPEC_THREAD_KEYRING")
 (:integer +key-spec-process-keyring+ "KEY_SPEC_PROCESS_KEYRING")
 (:integer +key-spec-session-keyring+ "KEY_SPEC_SESSION_KEYRING")
 (:integer +key-spec-user-keyring+ "KEY_SPEC_USER_KEYRING")
 (:integer +key-spec-user-session-keyring+ "KEY_SPEC_USER_SESSION_KEYRING")
 (:integer +key-spec-group-keyring+ "KEY_SPEC_GROUP_KEYRING")
 (:integer +key-spec-reqkey-auth-key+ "KEY_SPEC_REQKEY_AUTH_KEY")
 (:integer +key-reqkey-defl-no-change+ "KEY_REQKEY_DEFL_NO_CHANGE")
 (:integer +key-reqkey-defl-default+ "KEY_REQKEY_DEFL_DEFAULT")
 (:integer +key-reqkey-defl-thread-keyring+ "KEY_REQKEY_DEFL_THREAD_KEYRING")
 (:integer +key-reqkey-defl-process-keyring+ "KEY_REQKEY_DEFL_PROCESS_KEYRING")
 (:integer +key-reqkey-defl-session-keyring+ "KEY_REQKEY_DEFL_SESSION_KEYRING")
 (:integer +key-reqkey-defl-user-keyring+ "KEY_REQKEY_DEFL_USER_KEYRING")
 (:integer +key-reqkey-defl-user-session-keyring+ "KEY_REQKEY_DEFL_USER_SESSION_KEYRING")
 (:integer +key-reqkey-defl-group-keyring+ "KEY_REQKEY_DEFL_GROUP_KEYRING")
 (:integer +key-pos-view+ "KEY_POS_VIEW")
 (:integer +key-pos-read+ "KEY_POS_READ")
 (:integer +key-pos-write+ "KEY_POS_WRITE")
 (:integer +key-pos-search+ "KEY_POS_SEARCH")
 (:integer +key-pos-link+ "KEY_POS_LINK")
 (:integer +key-pos-setattr+ "KEY_POS_SETATTR")
 (:integer +key-pos-all+ "KEY_POS_ALL")
 (:integer +key-usr-view+ "KEY_USR_VIEW")
 (:integer +key-usr-read+ "KEY_USR_READ")
 (:integer +key-usr-write+ "KEY_USR_WRITE")
 (:integer +key-usr-search+ "KEY_USR_SEARCH")
 (:integer +key-usr-link+ "KEY_USR_LINK")
 (:integer +key-usr-setattr+ "KEY_USR_SETATTR")
 (:integer +key-usr-all+ "KEY_USR_ALL")
 (:integer +key-grp-view+ "KEY_GRP_VIEW")
 (:integer +key-grp-read+ "KEY_GRP_READ")
 (:integer +key-grp-write+ "KEY_GRP_WRITE")
 (:integer +key-grp-search+ "KEY_GRP_SEARCH")
 (:integer +key-grp-link+ "KEY_GRP_LINK")
 (:integer +key-grp-setattr+ "KEY_GRP_SETATTR")
 (:integer +key-grp-all+ "KEY_GRP_ALL")
 (:integer +key-oth-view+ "KEY_OTH_VIEW")
 (:integer +key-oth-read+ "KEY_OTH_READ")
 (:integer +key-oth-write+ "KEY_OTH_WRITE")
 (:integer +key-oth-search+ "KEY_OTH_SEARCH")
 (:integer +key-oth-link+ "KEY_OTH_LINK")
 (:integer +key-oth-setattr+ "KEY_OTH_SETATTR")
 (:integer +key-oth-all+ "KEY_OTH_ALL")
 (:integer +keyctl-get-keyring-id+ "KEYCTL_GET_KEYRING_ID")
 (:integer +keyctl-join-session-keyring+ "KEYCTL_JOIN_SESSION_KEYRING")
 (:integer +keyctl-update+ "KEYCTL_UPDATE")
 (:integer +keyctl-revoke+ "KEYCTL_REVOKE")
 (:integer +keyctl-chown+ "KEYCTL_CHOWN")
 (:integer +keyctl-setperm+ "KEYCTL_SETPERM")
 (:integer +keyctl-describe+ "KEYCTL_DESCRIBE")
 (:integer +keyctl-clear+ "KEYCTL_CLEAR")
 (:integer +keyctl-link+ "KEYCTL_LINK")
 (:integer +keyctl-unlink+ "KEYCTL_UNLINK")
 (:integer +keyctl-search+ "KEYCTL_SEARCH")
 (:integer +keyctl-read+ "KEYCTL_READ")
 (:integer +keyctl-instantiate+ "KEYCTL_INSTANTIATE")
 (:integer +keyctl-negate+ "KEYCTL_NEGATE")
 (:integer +keyctl-set-reqkey-keyring+ "KEYCTL_SET_REQKEY_KEYRING")
 (:integer +keyctl-set-timeout+ "KEYCTL_SET_TIMEOUT")
 (:integer +keyctl-assume-authority+ "KEYCTL_ASSUME_AUTHORITY")
 (:integer +keyctl-get-security+ "KEYCTL_GET_SECURITY")
 (:integer +keyctl-session-to-parent+ "KEYCTL_SESSION_TO_PARENT")
 (:integer +keyctl-reject+ "KEYCTL_REJECT")
 (:integer +keyctl-instantiate-iov+ "KEYCTL_INSTANTIATE_IOV")
 (:integer +keyctl-invalidate+ "KEYCTL_INVALIDATE")
 (:integer +keyctl-get-persistent+ "KEYCTL_GET_PERSISTENT")
 (:integer +keyctl-dh-compute+ "KEYCTL_DH_COMPUTE")
 (:integer +keyctl-pkey-query+ "KEYCTL_PKEY_QUERY")
 (:integer +keyctl-pkey-encrypt+ "KEYCTL_PKEY_ENCRYPT")
 (:integer +keyctl-pkey-decrypt+ "KEYCTL_PKEY_DECRYPT")
 (:integer +keyctl-pkey-sign+ "KEYCTL_PKEY_SIGN")
 (:integer +keyctl-pkey-verify+ "KEYCTL_PKEY_VERIFY")
 (:integer +keyctl-restrict-keyring+ "KEYCTL_RESTRICT_KEYRING")
 (:integer +keyctl-move+ "KEYCTL_MOVE")
 (:integer +keyctl-capabilities+ "KEYCTL_CAPABILITIES")
 (:integer +keyctl-watch-key+ "KEYCTL_WATCH_KEY")
 (:integer +keyctl-supports-encrypt+ "KEYCTL_SUPPORTS_ENCRYPT")
 (:integer +keyctl-supports-decrypt+ "KEYCTL_SUPPORTS_DECRYPT")
 (:integer +keyctl-supports-sign+ "KEYCTL_SUPPORTS_SIGN")
 (:integer +keyctl-supports-verify+ "KEYCTL_SUPPORTS_VERIFY")
 (:integer +keyctl-move-excl+ "KEYCTL_MOVE_EXCL")
 (:integer +keyctl-caps0-capabilities+ "KEYCTL_CAPS0_CAPABILITIES")
 (:integer +keyctl-caps0-persistent-keyrings+ "KEYCTL_CAPS0_PERSISTENT_KEYRINGS")
 (:integer +keyctl-caps0-diffie-hellman+ "KEYCTL_CAPS0_DIFFIE_HELLMAN")
 (:integer +keyctl-caps0-public-key+ "KEYCTL_CAPS0_PUBLIC_KEY")
 (:integer +keyctl-caps0-big-key+ "KEYCTL_CAPS0_BIG_KEY")
 (:integer +keyctl-caps0-invalidate+ "KEYCTL_CAPS0_INVALIDATE")
 (:integer +keyctl-caps0-restrict-keyring+ "KEYCTL_CAPS0_RESTRICT_KEYRING")
 (:integer +keyctl-caps0-move+ "KEYCTL_CAPS0_MOVE")
 (:integer +keyctl-caps1-ns-keyring-name+ "KEYCTL_CAPS1_NS_KEYRING_NAME")
 (:integer +keyctl-caps1-ns-key-tag+ "KEYCTL_CAPS1_NS_KEY_TAG")
 (:integer +keyctl-caps1-notifications+ "KEYCTL_CAPS1_NOTIFICATIONS")
 ;; (:structure keyctl-dh-params ("struct keyctl_dh_params"
 ;;                               (key-serial-t priv "key_serial_t" "priv")
 ;;                               (key-serial-t prime "key_serial_t" "prime")
 ;;                               (key-serial-t base "key_serial_t" "base")))
 (:structure keyctl-kdf-params ("struct keyctl_kdf_params"
                                (c-string hashname "char *" "hashname")
                                (c-string otherinfo "char *" "otherinfo")
                                (unsigned-int otherinfolen "uint32_t" "otherinfolen")
                                ((array unsigned-int 8) spare "uint32_t" "__spare[8]")))
 (:structure keyctl-pkey-query ("struct keyctl_pkey_query"
                                (unsigned-int supported-ops "unsigned int" "supported_ops")
                                (unsigned-int key-size "unsigned int" "key_size")
                                (unsigned-short max-data-size "unsigned short" "max_data_size")
                                (unsigned-short max-sig-size "unsigned short" "max_sig_size")
                                (unsigned-short max-enc-size "unsigned short" "max_enc_size")
                                (unsigned-short max-dec-size "unsigned short" "max_dec_size")
                                ((array unsigned-int 10) spare "unsigned int" "__spare[10]"))))
