[workspace]
resolver = "2"
members = ["crates/*"]
[workspace.package]
version = "0.1.0"
authors = ["Richard Westhaver <ellis@rwest.io>"]
edition = "2024"
[profile.release]
lto = true
panic = "abort"
[workspace.dependencies]
tokio = "1.45"
tokio-util = "0.7.15"
tokio-stream = "0.1.17"
serde = "1"
log = "0.4.27"
# bindgen = "0.71.1"
# [profile.dev.package."*"]
# opt-level = 2