;;; blas.lisp --- BLAS

;; BLAS Fortran bindings

;;; Code:
(defpackage :blas
  (:use :cl :std :log :sb-alien)
  (:export :load-openblas :load-blas :load-lapack :load-lapacke :load-cblas
   :dgemm
   :xdouble
   :complex-float
   :complex-double
   :complex-xdouble))

(in-package :blas)

(define-alien-loader openblas "/usr/lib/")
;; usually just points to libopenblas.so
(define-alien-loader blas "/usr/lib/")
(define-alien-loader cblas "/usr/lib/")

;;; CBLAS
;; these are part of CBLAS
(defar openblas-get-num-threads int)
(defar openblas-set-num-threads-local int (n int))
(defar openblas-get-num-procs int)
(defar openblas-get-config c-string)
(defar openblas-get-corename c-string)
(defar openblas-set-threads-callback-function void (* (function void)))
;; (defar openblas-setaffinity int (thread-idx int) (cpusetsize size-t) (cpu-set (* cpu-set-t)))
;; (defar openblas-getaffinity int (thread-idx int) (cpusetsize size-t) (cpu-set (* cpu-set-t)))
(defar openblas-get-parallel int)
(define-alien-enum (openblas-parallel int)
  :sequential 0
  :thread 1
  :openmp 2)

;; this is defined literally (no BLASFUNC)
(define-alien-routine ("openblas_set_num_threads_" openblas-set-num-threads) void (n int :copy))

;;; Types
;; FLOATRET = float
;; blasint = int
;; BLASLONG = long
;; BLASULONG unsigned-long
;; xdouble double?
;; bfloat16 unsigned-short

(define-alien-type xdouble (array unsigned-long 2))
(define-alien-type complex-float (array float 2))
(define-alien-type complex-double (array double 2))
(define-alien-type complex-xdouble (array xdouble 2))
(define-alien-type openblas-dojob-callback 
  (function void int (* t) int))
(define-alien-type openblas-threads-callback
    (function void int (* openblas-dojob-callback) int size-t (* t) int))

;;; Shared Macros      
(defmacro defblas (sym ret &rest args)
  `(defar (,(concatenate 'string (string-downcase (symbol-name sym)) "_") ,sym) ,ret ,@args))

#|
 XERBLA  is an error handler for the LAPACK routines.
 It is called by an LAPACK routine if an input parameter has an
 invalid value.  A message is printed and execution stops.

 Installers may consider modifying the STOP statement in order to
 call system-specific exception-handling facilities.
|#
(defblas xerbla int
  (srname c-string)
  (info int :copy)
  (nout int))

;;; Level 1
(macrolet ((blas5 (sym type ret &rest args)
             `(defblas ,sym ,ret 
                        (n int :copy) 
                        ,@args 
                        (x (* ,type)) (incx int :copy) 
                        (y (* ,type)) (incy int :copy)))
           (blas5s (sym &rest args)
             `(blas5 ,sym float void ,@args))
           (blas5d (sym &rest args)
             `(blas5 ,sym double void ,@args))
           (blas5bf16 (sym &rest args)
             `(blas5 ,sym unsigned-short void ,@args))
           (blas5c (sym &rest args)
             `(blas5 ,sym complex-float void ,@args))
           (blas5z (sym &rest args)
             `(blas5 ,sym complex-double void ,@args))
           (blas5q (sym &rest args)
             `(blas5 ,sym xdouble void ,@args))
           (blas5x (sym &rest args)
             `(blas5 ,sym complex-xdouble void ,@args))
           (blas3 (sym type ret)
             `(defblas ,sym ,ret (n int :copy) (x (* ,type)) (incx int :copy)))
           (blas3s (sym ret &rest args)
             `(blas3 ,sym float ,ret ,@args))
           (blas3d (sym ret &rest args)
             `(blas3 ,sym double ,ret ,@args))
           (blas3bf16 (sym ret &rest args)
             `(blas3 ,sym unsigned-short ,ret ,@args))
           (blas3c (sym ret &rest args)
             `(blas3 ,sym complex-float ,ret ,@args))
           (blas3z (sym ret &rest args)
             `(blas3 ,sym complex-double ,ret ,@args))
           (blas3q (sym ret &rest args)
             `(blas3 ,sym xdouble ,ret ,@args))
           (blas3x (sym ret &rest args)
             `(blas3 ,sym complex-xdouble ,ret ,@args))
           (blas7 (sym type)
             `(defblas ,sym void 
                        (n int :copy) 
                        (x (* ,type)) (incx int :copy) 
                        (y (* ,type)) (incy int :copy)
                        (za (* ,type)) (zb (* ,type))))
           (blas4 (sym type)
             `(defblas ,sym void 
                        (n int :copy) 
                        (a (* ,type)) 
                        (x (* ,type)) (incx int :copy)))
           (blas4* (sym type)
             `(defblas ,sym void 
                        (a (* ,type)) 
                        (b (* ,type)) 
                        (c (* ,type)) 
                        (s (* ,type))))
           (blas5* (sym type)
             `(defblas ,sym void 
                        (a (* ,type)) 
                        (b (* ,type)) 
                        (x (* ,type)) 
                        (y (* ,type)) 
                        (s (* ,type))))
           (blas6 (sym type)
             `(defblas ,sym void 
                        (n int :copy) 
                        (x (* ,type)) (incx int :copy) 
                        (y (* ,type)) (incy int :copy) 
                        (s (* ,type)))))
  (blas5 sdot float float)
  (blas5 sdsdot float float (a (* float)))
  (blas5 dsdot float double)
  (blas5 ddot float double)
  (blas5 qdot xdouble xdouble)
  (blas5 sbdot unsigned-short float)

  (defblas sbstobf16 void
            (n int :copy)
            (x (* float))
            (incx int :copy)
            (y (* unsigned-short))
            (incy int :copy))

  (defblas sbdtobf16 void
            (n int :copy)
            (x (* double))
            (incx int :copy)
            (y (* unsigned-short))
            (incy int :copy))

  (defblas sbf16tos void
            (n int :copy)
            (x (* unsigned-short))
            (incx int :copy)
            (y (* float))
            (incy int :copy))

  (defblas dbf16tod void
            (n int :copy)
            (x (* unsigned-short))
            (incx int :copy)
            (y (* double))
            (incy int :copy))

  (defblas cdotu void
            (z (* complex-float))
            (n int :copy)
            (x (* float))
            (incx int :copy)
            (y (* float))
            (incy int :copy))

  (defblas cdotc void
            (z (* complex-float))
            (n int :copy)
            (x (* float))
            (incx int :copy)
            (y (* float))
            (incy int :copy))

  (defblas zdotu void
            (z (* complex-double))
            (n int :copy)
            (x (* double))
            (incx int :copy)
            (y (* double))
            (incy int :copy))

  (defblas zdotc void
            (z (* complex-double))
            (n int :copy)
            (x (* double))
            (incx int :copy)
            (y (* double))
            (incy int :copy))

  (defblas xdotu void
            (z (* complex-xdouble))
            (n int :copy)
            (x (* xdouble))
            (incx int :copy)
            (y (* xdouble))
            (incy int :copy))

  (defblas xdotc void
            (z (* complex-xdouble))
            (n int :copy)
            (x (* xdouble))
            (incx int :copy)
            (y (* xdouble))
            (incy int :copy))

  ;; y = ax + y
  (blas5s saxpy (a float :copy))
  (blas5d daxpy (a double :copy))
  (blas5q qaxpy (a xdouble :copy))
  (blas5c caxpy (a complex-float :copy))
  (blas5z zaxpy (a complex-double :copy))
  (blas5x xaxpy (a complex-xdouble :copy))
  (blas5s caxpyc (a float :copy))
  (blas5d zaxpyc (a double :copy))
  (blas5q xaxpyc (a xdouble :copy))
  (blas5s scopy)
  (blas5d dcopy)
  (blas5q qcopy)
  (blas5c ccopy)
  (blas5z zcopy)
  (blas5x xcopy)
  (blas5s sswap)
  (blas5d dswap)
  (blas5q qswap)
  (blas5c cswap)
  (blas5z zswap)
  (blas5x xswap)
  (blas3s sasum float)
  (blas3s scasum float)
  (blas3d dasum double)
  (blas3q qasum xdouble)
  (blas3d dzasum double)
  (blas3q qxasum xdouble)
  (blas3s ssum float)
  (blas3s scsum float)
  (blas3d dsum double)
  (blas3q qsum xdouble)
  (blas3d dzsum double)
  (blas3q qxsum xdouble)
  (blas3s isamax int)
  (blas3d idamax int)
  (blas3q iqamax int)
  (blas3s icamax int)
  (blas3d izamax int)
  (blas3q ixamax int)
  (blas3s ismax int)
  (blas3d idmax int)
  (blas3q iqmax int)
  (blas3s icmax int)
  (blas3d izmax int)
  (blas3q ixmax int)
  (blas3s isamin int)
  (blas3d idamin int)
  (blas3q iqamin int)
  (blas3s icamin int)
  (blas3d izamin int)
  (blas3q ixamin int)
  (blas3s ismin int)
  (blas3d idmin int)
  (blas3q iqmin int)
  (blas3s icmin int)
  (blas3d izmin int)
  (blas3q ixmin int)
  (blas3s samax float)
  (blas3d damax double)
  (blas3q qamax xdouble)
  (blas3s scamax float)
  (blas3d dzamax double)
  (blas3q qxamax xdouble)
  (blas3s samin float)
  (blas3d damin double)
  (blas3q qamin xdouble)
  (blas3s scamin float)
  (blas3d dzamin double)
  (blas3q qxamin xdouble)
  (blas3s smax float)
  (blas3d dmax double)
  (blas3q qmax xdouble)
  (blas3s scmax float)
  (blas3d dzmax double)
  (blas3q qxmax xdouble)
  (blas3s smin float)
  (blas3d dmin double)
  (blas3q qmin xdouble)
  (blas3s scmin float)
  (blas3d dzmin double)
  (blas3q qxmin xdouble)
  (blas4 sscal float)
  (blas4 dscal double)
  (blas4 qscal xdouble)
  (blas4 cscal float)
  (blas4 zscal double)
  (blas4 xscal xdouble)
  (blas4 csscal float)
  (blas4 zdscal double)
  (blas4 xqscal xdouble)
  (blas3s snrm2 float)
  (blas3s scnrm2 float)
  (blas3d dnrm2 double)
  (blas3q qnrm2 xdouble)
  (blas3d dznrm2 double)
  (blas3q qxnrm2 xdouble)
  (blas7 srot float) 
  (blas7 drot double)
  (blas7 qrot xdouble)
  (blas7 csrot float)
  (blas7 zdrot double)
  (blas7 xqrot xdouble)
  (blas4* srotg float)
  (blas4* drotg double)
  (blas4* qrotg xdouble)
  (blas4* crotg float)
  (blas4* zrotg double)
  (blas4* xrotg xdouble)
  (blas5* srotmg float)
  (blas5* drotmg double)
  (blas6 srotm float)
  (blas6 drotm double)
  (blas6 qrotm xdouble))

;;; Level 2
(macrolet ((blas9 (sym type)
             `(defblas ,sym void 
                        (m int :copy) 
                        (n int :copy) 
                        (alpha ,type :copy)
                        (x (* ,type)) (incx int :copy) 
                        (y (* ,type)) (incy int :copy) 
                        (a (* ,type)) (lda int :copy)))
           (blas11 (sym type)
             `(defblas ,sym void
                        (trans char :copy)
                        (m int :copy)
                        (n int :copy)
                        (alpha ,type :copy)
                        (a (* ,type)) (lda int :copy)
                        (x (* ,type)) (incx int :copy) 
                        (beta float :copy)
                        (y (* ,type)) (incy int :copy)))
           (blas8 (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (trans char :copy)
                        (diag char :copy)
                        (n int :copy)
                        (a (* ,type)) (lda int :copy)
                        (x (* ,type)) (incx int :copy)))
           (blas7 (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (trans char :copy)
                        (diag char :copy)
                        (n int :copy)
                        (ap (* ,type))
                        (x (* ,type)) (incx int :copy)))
           (blas9* (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (trans char :copy)
                        (diag char :copy)
                        (n int :copy)
                        (k int :copy)
                        (a (* ,type)) (lda int :copy)
                        (x (* ,type)) (incx int :copy)))
           (blas10 (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (n int :copy)
                        (alpha ,type :copy)
                        (a (* ,type)) (lda int :copy)
                        (x (* ,type)) (incx int :copy) 
                        (beta ,type :copy)
                        (y (* ,type)) (incy int :copy)))
           (blas9** (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (n int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (x (* ,type)) (incx int :copy)
                        (beta float :copy)
                        (y (* ,type)) (incy int :copy)))
           (blas7* (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (n int :copy)
                        (x (* ,type)) (incx int :copy)
                        (a (* ,type)) (lda int :copy)))
           (blas9*** (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (n int :copy)
                        (alpha ,type :copy)
                        (x (* ,type)) (incx int :copy)
                        (y (* ,type)) (incy int :copy)
                        (a (* ,type)) (lda int :copy)))
           (blas6* (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (n int :copy)
                        (alpha ,type :copy)
                        (x (* ,type)) (incx int :copy)
                        (a (* ,type))))
           (blas8* (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (n int :copy)
                        (alpha ,type :copy)
                        (x (* ,type)) (incx int :copy)
                        (y (* ,type)) (incy int :copy)
                        (a (* ,type))))
           (blas7** (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (n int :copy)
                        (alpha ,type :copy)
                        (x (* ,type)) (incx int :copy)
                        (a (* ,type)) (lda int :copy)))
           (blas13 (sym type)
             `(defblas ,sym void
                        (trans char :copy)
                        (m int :copy)
                        (n int :copy)
                        (kl int :copy)
                        (ku int :copy)
                        (alpha ,type :copy)
                        (a (* ,type)) (lda int :copy)
                        (x (* ,type)) (incx int :copy) 
                        (beta ,type :copy)
                        (y (* ,type)) (incy int :copy))))
  (blas9 sger float) 
  (blas9 dger double)
  (blas9 qger xdouble)
  (blas9 cgeru float)
  (blas9 cgerc float)
  (blas9 zgeru double)
  (blas9 zgerc double)
  (blas9 xgeru xdouble)
  (blas9 xgerc xdouble)
  (defblas sbgemv void
            (trans char :copy)
            (m int :copy)
            (n int :copy)
            (alpha float :copy)
            (a (* unsigned-short)) (lda int :copy)
            (x (* unsigned-short)) (incx int :copy)
            (beta float :copy)
            (y (* float)) (incy int :copy))
  (blas11 sgemv float)
  (blas11 dgemv double)
  (blas11 qgemv xdouble)
  (blas11 cgemv float)
  (blas11 zgemv double)
  (blas11 xgemv xdouble)
  (blas8 strsv float)
  (blas8 dtrsv double)
  (blas8 qtrsv xdouble)
  (blas8 ctrsv float)
  (blas8 ztrsv double)
  (blas8 xtrsv xdouble)
  (blas8 strmv float)
  (blas8 dtrmv double)
  (blas8 qtrmv xdouble)
  (blas8 ctrmv float)
  (blas8 ztrmv double)
  (blas8 xtrmv xdouble)
  (blas7 stpsv float)
  (blas7 dtpsv double)
  (blas7 qtpsv xdouble)
  (blas7 ctpsv float)
  (blas7 ztpsv double)
  (blas7 xtpsv xdouble)
  (blas7 stpmv float)
  (blas7 dtpmv double)
  (blas7 qtpmv xdouble)
  (blas7 ctpmv float)
  (blas7 ztpmv double)
  (blas7 xtpmv xdouble)
  (blas9* stbmv float)
  (blas9* dtbmv double)
  (blas9* qtbmv xdouble)
  (blas9* ctbmv float)
  (blas9* ztbmv double)
  (blas9* xtbmv xdouble)
  (blas9* stbsv float)
  (blas9* dtbsv double)
  (blas9* qtbsv xdouble)
  (blas9* ctbsv float)
  (blas9* ztbsv double)
  (blas9* xtbsv xdouble)
  (blas10 ssymv float)
  (blas10 dsymv double)
  (blas10 qsymv xdouble)
  (blas10 csymv float)
  (blas10 zsymv double)
  (blas10 xsymv xdouble)
  (blas9** sspmv float)
  (blas9** dspmv double)
  (blas9** qspmv xdouble)
  (blas9** cspmv float)
  (blas9** zspmv double)
  (blas9** xspmv xdouble)
  (blas7* ssyr float)
  (blas7* dsyr double)
  (blas7* qsyr xdouble)
  (blas7* csyr float)
  (blas7* zsyr double)
  (blas7* xsyr xdouble)
  (blas9*** ssyr2 float)
  (blas9*** dsyr2 double)
  (blas9*** qsyr2 xdouble)
  (blas9*** csyr2 float)
  (blas9*** zsyr2 double)
  (blas9*** xsyr2 xdouble)
  (blas6* sspr float)
  (blas6* dspr double)
  (blas6* qspr xdouble)
  (blas6* cspr float)
  (blas6* zspr double)
  (blas6* xspr xdouble)
  (blas8* sspr2 float)
  (blas8* dspr2 double)
  (blas8* qspr2 xdouble)
  (blas8* cspr2 float)
  (blas8* zspr2 double)
  (blas8* xspr2 xdouble)
  (blas7** cher float)
  (blas7** zher double)
  (blas7** xher xdouble)
  (blas6* chpr float)
  (blas6* zhpr double)
  (blas6* xhpr xdouble)
  (blas9*** cher2 float)
  (blas9*** zher2 double)
  (blas9*** xher2 xdouble)
  (blas8* chpr2 float)
  (blas8* zhpr2 double)
  (blas8* xhpr2 xdouble)
  (blas10 chemv float)
  (blas10 zhemv double)
  (blas10 xhemv xdouble)
  (blas9** chpmv float)
  (blas9** zhpmv double)
  (blas9** xhpmv xdouble)
  ;; *norm not part of spec
  (defblas snorm int (uplo char :copy) (n int :copy) (alpha int :copy) (x (* float)) (incx int :copy))
  (defblas dnorm int (uplo char :copy) (n int :copy) (alpha int :copy) (x (* double)) (incx int :copy))
  (defblas cnorm int (uplo char :copy) (n int :copy) (alpha int :copy) (x (* float)) (incx int :copy))
  (defblas znorm int (uplo char :copy) (n int :copy) (alpha int :copy) (x (* double)) (incx int :copy))
  (blas13 sgbmv float)
  (blas13 dgbmv double)
  (blas13 qgbmv xdouble)
  (blas13 cgbmv float)
  (blas13 zgbmv double)
  (blas13 xgbmv xdouble)
  (blas11 ssbmv float)
  (blas11 dsbmv double)
  (blas11 qsbmv xdouble)
  (blas11 csbmv float)
  (blas11 zsbmv double)
  (blas11 xsbmv xdouble)
  (blas11 chbmv float)
  (blas11 zhbmv double)
  (blas11 xhbmv xdouble))

;;; Level 3
(macrolet ((blas13 (sym type)
             `(defblas ,sym void
                        (transa char :copy)
                        (transb char :copy)
                        (m int :copy)
                        (n int :copy)
                        (k int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (b (* ,type))
                        (ldb int :copy)
                        (beta ,type :copy)
                        (c (* ,type))
                        (ldc int :copy)))
           (blas13* (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (transa char :copy)
                        (transb char :copy)
                        (n int :copy)
                        (k int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (b (* ,type))
                        (ldb int :copy)
                        (beta ,type :copy)
                        (c (* ,type))
                        (ldc int :copy)))
           (blas11 (sym type)
             `(defblas ,sym void
                        (side char :copy)
                        (uplo char :copy)
                        (transa char :copy)
                        (diag char :copy)
                        (m int :copy)
                        (n int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (b (* ,type))
                        (ldb int :copy)))
           (blas12 (sym type)
             `(defblas ,sym void
                        (side char :copy)
                        (uplo char :copy)
                        (m int :copy)
                        (n int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (b (* ,type))
                        (ldb int :copy)
                        (beta ,type :copy)
                        (c (* ,type))
                        (ldc int :copy)))
           (blas10 (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (trans char :copy)
                        (n int :copy)
                        (k int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (beta ,type :copy)
                        (c (* ,type))
                        (ldc int :copy)))
           (blas12* (sym type)
             `(defblas ,sym void
                        (uplo char :copy)
                        (trans char :copy)
                        (n int :copy)
                        (k int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (b (* ,type))
                        (ldb int :copy)
                        (beta ,type :copy)
                        (c (* ,type))
                        (ldc int :copy)))
           (blas12% (sym type)
             `(defblas ,sym int
                        (uplo char :copy)
                        (trans char :copy)
                        (n int :copy)
                        (k int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (b (* ,type))
                        (ldb int :copy)
                        (beta ,type :copy)
                        (c (* ,type))
                        (ldc int :copy)))
           (blas8 (sym type)
             `(defblas ,sym int
                        (uplo char :copy)
                        (n int :copy)
                        (k int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (b (* ,type))
                        (ldb int :copy)))
           (blas12** (sym type)
             `(defblas ,sym int
                        (uplo char :copy)
                        (trans char :copy)
                        (n int :copy)
                        (k int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (beta ,type :copy)
                        (b (* ,type))
                        (ldb int :copy)
                        (c (* ,type))
                        (ldc int :copy)))
           (blas15 (sym type)
             `(defblas ,sym int
                        (uplo char :copy)
                        (trans char :copy)
                        (m int :copy)
                        (n int :copy)
                        (k int :copy)
                        (alpha ,type :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (b (* ,type))
                        (ldb int :copy)
                        (c (* ,type))
                        (ldc int :copy)
                        (beta ,type :copy)
                        (x (* ,type))
                        (incx int :copy))))
  (defblas sbgemm void
            (transa char :copy)
            (transb char :copy)
            (m int :copy)
            (n int :copy)
            (k int :copy)
            (alpha float :copy)
            (a (* unsigned-short))
            (lda int :copy)
            (b (* unsigned-short))
            (ldb int :copy)
            (beta float :copy)
            (c (* float))
            (ldc int :copy))
  (blas13 sgemm float)
  (blas13 dgemm double)
  (blas13 qgemm xdouble)
  (blas13 cgemm float)
  (blas13 zgemm double)
  (blas13 xgemm xdouble)
  (blas13 cgemm3m float)
  (blas13 zgemm3m double)
  (blas13 xgemm3m xdouble)
  (blas13* sgemmt float)
  (blas13* dgemmt double)
  (blas13* cgemmt float)
  (blas13* zgemmt double)
  (blas13* sge2mm float)
  (blas13* dge2mm double)
  (blas13* cge2mm float)
  (blas13* zge2mm double)
  (blas11 strsm float)
  (blas11 dtrsm double)
  (blas11 qtrsm xdouble)
  (blas11 ctrsm float)
  (blas11 ztrsm double)
  (blas11 xtrsm xdouble)
  (blas11 strmm float)
  (blas11 dtrmm double)
  (blas11 qtrmm xdouble)
  (blas11 ctrmm float)
  (blas11 ztrmm double)
  (blas11 xtrmm xdouble)
  (blas12 ssymm float)
  (blas12 dsymm double)
  (blas12 qsymm xdouble)
  (blas12 csymm float)
  (blas12 zsymm double)
  (blas12 xsymm xdouble)
  (blas12 csymm3m float)
  (blas12 zsymm3m double)
  (blas12 xsymm3m xdouble)
  (blas10 ssyrk float)
  (blas10 dsyrk double)
  (blas10 qsyrk xdouble)
  (blas10 csyrk float)
  (blas10 zsyrk double)
  (blas10 xsyrk xdouble)
  (blas12* ssyr2k float)
  (blas12* dsyr2k double)
  (blas12* qsyr2k xdouble)
  (blas12* csyr2k float)
  (blas12* zsyr2k double)
  (blas12* xsyr2k xdouble)
  (blas12* chemm float)
  (blas12* zhemm double)
  (blas12* xhemm xdouble)
  (blas12* chemm3m float)
  (blas12* zhemm3m double)
  (blas12* xhemm3m xdouble)
  (blas10 cherk float)
  (blas10 zherk double)
  (blas10 xherk xdouble)
  (blas12* cher2k float)
  (blas12* zher2k double)
  (blas12* xher2k xdouble)
  (blas12% cher2m float)
  (blas12% zher2m double)
  (blas12% xher2m xdouble)
  (blas8 sgemt float)
  (blas8 dgemt double)
  (blas8 cgemt float)
  (blas8 zgemt double)
  (blas12** sgema float)
  (blas12** dgema double)
  (blas12** cgema float)
  (blas12** zgema double)
  (blas12** sgems float)
  (blas12** dgems double)
  (blas12** cgems float)
  (blas12** zgems double)
  (blas15 sgemc float)
  (blas15 dgemc double)
  (blas15 qgemc xdouble)
  (blas15 cgemc float)
  (blas15 zgemc double)
  (blas15 xgemc xdouble))

;;; Lapack routines
(macrolet ((lap6 (sym type)
             `(defblas ,sym int 
                        (m int :copy) 
                        (n int :copy) 
                        (a (* ,type)) 
                        (lda int :copy)
                        (ipiv (* int))
                        (info int :copy)))
           (lap7 (sym type)
             `(defblas ,sym int
                        (n int :copy) 
                        (a (* ,type)) 
                        (lda int :copy)
                        (k1 int :copy)
                        (k2 int :copy)
                        (ipiv (* int))
                        (incx int :copy)))
           (lap9 (sym type)
             `(defblas ,sym int
                        (trans char :copy)
                        (n int :copy)
                        (nrhs int :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (ipiv (* int))
                        (b (* ,type))
                        (ldb int :copy)
                        (info int :copy)))
           (lap8 (sym type)
             `(defblas ,sym int
                        (n int :copy)
                        (nrhs int :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (ipiv (* int))
                        (b (* ,type))
                        (ldb int :copy)
                        (info int :copy)))
           (lap5 (sym type)
             `(defblas ,sym int
                        (uplo char :copy)
                        (n int :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (info int :copy)))
           (lap8* (sym type)
             `(defblas ,sym int
                        (uplo char :copy)
                        (n int :copy)
                        (nrhs int :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (b (* ,type))
                        (ldb int :copy)
                        (info int :copy)))
           (lap6* (sym type)
             `(defblas ,sym int
                        (uplo char :copy)
                        (diag char :copy)
                        (n int :copy)
                        (a (* ,type))
                        (lda int :copy)
                        (info int :copy))))
  (lap6 sgetf2 float)
  (lap6 dgetf2 double)
  (lap6 qgetf2 xdouble)
  (lap6 cgetf2 float)
  (lap6 zgetf2 double)
  (lap6 xgetf2 xdouble)
  (lap6 sgetrf float)
  (lap6 dgetrf double)
  (lap6 qgetrf xdouble)
  (lap6 cgetrf float)
  (lap6 zgetrf double)
  (lap6 xgetrf xdouble)
  (lap7 slaswp float)
  (lap7 dlaswp double)
  (lap7 qlaswp xdouble)
  (lap7 claswp float)
  (lap7 zlaswp double)
  (lap7 xlaswp xdouble)
  (lap9 sgetrs float)
  (lap9 dgetrs double)
  (lap9 qgetrs xdouble)
  (lap9 cgetrs float)
  (lap9 zgetrs double)
  (lap9 xgetrs xdouble)
  (lap8 sgesv float)
  (lap8 dgesv double)
  (lap8 qgesv xdouble)
  (lap8 cgesv float)
  (lap8 zgesv double)
  (lap8 xgesv xdouble)
  (lap5 spotf2 float)
  (lap5 dpotf2 double)
  (lap5 qpotf2 xdouble)
  (lap5 cpotf2 float)
  (lap5 zpotf2 double)
  (lap5 xpotf2 xdouble)
  (lap5 spotrf float)
  (lap5 dpotrf double)
  (lap5 qpotrf xdouble)
  (lap5 cpotrf float)
  (lap5 zpotrf double)
  (lap5 xpotrf xdouble)
  (lap5 spotri float)
  (lap5 dpotri double)
  (lap5 qpotri xdouble)
  (lap5 cpotri float)
  (lap5 zpotri double)
  (lap5 xpotri xdouble)
  (lap8* spotrs float)
  (lap8* dpotrs double)
  (lap8* qpotrs xdouble)
  (lap8* cpotrs float)
  (lap8* zpotrs double)
  (lap8* xpotrs xdouble)
  (lap5 slauu2 float)
  (lap5 dlauu2 double)
  (lap5 qlauu2 xdouble)
  (lap5 clauu2 float)
  (lap5 zlauu2 double)
  (lap5 xlauu2 xdouble)
  (lap5 slauum float)
  (lap5 dlauum double)
  (lap5 qlauum xdouble)
  (lap5 clauum float)
  (lap5 zlauum double)
  (lap5 xlauum xdouble)
  (lap6* strti2 float)
  (lap6* dtrti2 double)
  (lap6* qtrti2 xdouble)
  (lap6* ctrti2 float)
  (lap6* ztrti2 double)
  (lap6* xrti2 xdouble)
  (lap6* strti float)
  (lap6* dtrti double)
  (lap6* qtrti xdouble)
  (lap6* ctrti float)
  (lap6* ztrti double)
  (lap6* xtrti xdouble)
  (defblas slamch float (cmach char :copy))
  (defblas dlamch double (cmach char :copy))
  (defblas qlamch xdouble (cmach char :copy))
  (defblas slamc3 float (a float :copy) (b float :copy))
  (defblas dlamc3 double (a double :copy) (b double :copy))
  (defblas qlamc3 xdouble (a xdouble :copy) (b xdouble :copy)))

;;; BLAS extensions
;; ref: https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-fortran/2025-1/overview.html
;; saxpby daxpby caxpby zaxpby
;; somatcopy domatcopy comatcopy zomatcopy
;; simatcopy dimatcopy cimatcopy zimatcopy
;; sgeadd dgeadd cgeadd zgeadd
