;;; async.lisp --- Async Tests

;; 

;;; Code:
(in-package :std/tests)
(in-suite :std)

(deftest futures ()
  (with-temp-pool (4)
    (let ((a (future 3))
          (b (future 4)))
      (is (= 7 (+ (await a) (await b)))))
    (let ((a (future 5)))
      (sleep 0.2)
      (is (fulfilledp a))
      (is (= 5 (await a))))
    (let ((a (future (sleep 0.4) 3)))
      (is (not (fulfilledp a)))
      (sleep 0.2)
      (is (eq nil (fulfill a 4)))
      (is (not (fulfilledp a)))
      (is (= 3 (await a))))
    (let ((a (future 3)))
      (sleep 0.2)
      (is (eq nil (fulfill a 9)))
      (is (= 3 (await a))))))

(deftest promises ()
  (let ((a (promise))
        (b (promise)))
    (fulfill a 3)
    (fulfill b 4)
    (is (= 12 (* (await a) (await b)))))
  (let ((a (promise)))
    (is (eq t (fulfill a 3)))
    (is (eq nil (fulfill a 4)))
    (is (= 3 (await a)))))

(deftest speculations ()
  (let ((*memo* (make-queue)))
    (with-temp-pool (2)
      (await (future (sleep 0.25)))
      (await (future (sleep 0.50)))
      (await (std/async::speculate (push-queue* 3 *memo*)))
      (await (future (push-queue* 4 *memo*))))
    (is (eql 3 (pop-queue *memo*)))
    (is (eql 4 (pop-queue *memo*)))))

(deftest flood (:skip t)
  (with-temp-pool (4)
    (let* ((a (promise))
           (futures (loop for i from 0 below 4 collect (await a))))
      (is (notany #'fulfilledp futures))
      (sleep 0.5)
      (is (notany #'fulfilledp futures))
      (fulfill a 4)
      ;; FIX 2025-08-11: 
      (print futures)
      (is (every #'fulfilledp futures))
      ;; (isevery (lambda (x) (= x 4)) (mapcar #'await futures))
      )))
      
(defpun async-test-foo ()
  "An asynchronous test function."
  ;; plet/plet-if are local to DEFPUN
  (plet-if #'numberp ((a 1) (b 1))
           (is= 2 (+ a b))))

(deftest defpuns ()
  (with-temp-pool (2)
    (async-test-foo)))

(deftest cognates ()
  (sb-ext:gc :full t)
  (with-temp-pool ((num-cpus))
    (is= 10 (preduce '+ #(1 2 3 4)))
    (is (por nil nil nil t)))
  (sb-ext:gc :full t)
  (let ((foo (iota 100)))
    (sleep 0.1)
    (with-temp-pool ((num-cpus))
      (isnt (pand t 1 #() 'foo nil))
      ;; pfind seems to return before all threads do.. (false-negative)
      (is= 99 (pfind 99 foo))
      (is= 14 (pmap-reduce #'1+ #'+ #(1 2 3 4)))
      (is= 1 (aref (pmap 'vector #'1+ '(0 0)) 0))
      ;; FIX 2025-09-02: pquantifier
      (is (pevery #'atom (iota 4)))
      (is (psome #'vectorp (list nil t #() 'foo)))
      )))
