;;; async.lisp --- Async Tests

;; 

;;; Code:
(in-package :std/tests)
(in-suite :std)

(deftest futures ()
  (with-temp-pool (4)
    (let ((a (future 3))
          (b (future 4)))
      (is (= 7 (+ (await a) (await b)))))
    (let ((a (future 5)))
      (sleep 0.2)
      (is (fulfilledp a))
      (is (= 5 (await a))))
    (let ((a (future (sleep 0.4) 3)))
      (is (not (fulfilledp a)))
      (sleep 0.2)
      (is (eq nil (fulfill a 4)))
      (is (not (fulfilledp a)))
      (is (= 3 (await a))))
    (let ((a (future 3)))
      (sleep 0.2)
      (is (eq nil (fulfill a 9)))
      (is (= 3 (await a))))))

(deftest promises ()
  (let ((a (promise))
        (b (promise)))
    (fulfill a 3)
    (fulfill b 4)
    (is (= 12 (* (await a) (await b)))))
  (let ((a (promise)))
    (is (eq t (fulfill a 3)))
    (is (eq nil (fulfill a 4)))
    (is (= 3 (await a)))))

(deftest speculations ()
  (setf *memo* (make-queue))
  (with-temp-pool (2)
    (sleep 0.2)
    (future (sleep 0.25))
    (future (sleep 0.50))
    (sleep 0.125)
    (std/async::speculate (push-queue 3 *memo*))
    (future (push-queue 4 *memo*))
    (sleep 0.5)
    (is (eql 4 (pop-queue *memo*)))
    (is (eql 3 (pop-queue *memo*)))))

(deftest flood ()
  (with-temp-pool (4)
    (let* ((a (promise))
           (futures (loop for i from 0 below 100 collect (future (await a)))))
      (is (notany #'fulfilledp futures))
      (sleep 0.5)
      (is (notany #'fulfilledp futures))
      (fulfill a 4)
      (sleep 1.0)
      ;; FIX 2025-08-11: 
      (is (every #'fulfilledp futures))
      ;; (is (every (lambda (x) (= x 4)) (mapcar #'await futures)))
      )))
