;;; ppcre.lisp --- PPCRE Tests

;; The tests in this file test PPCRE against testdata generated by
;; the Perl program `perltest.pl' from the input file `testinput' in
;; order to check compatibility with Perl and correctness of the
;; regex engine.

;;; Code:
(in-package :std/tests)

(defvar *this-file* (load-time-value
                     (or #.*compile-file-pathname* *load-pathname*))
  "The location of this source file.")

(defmacro %do-tests ((name &optional show-progress-p) &body body)
  "Helper macro which repeatedly executes BODY until the code in body
calls the function DONE.  It is assumed that each invocation of BODY
will be the execution of one test which returns NIL in case of success
and list of string describing errors otherwise.

The macro prints a simple progress indicator \(one dots for ten tests)
to *STANDARD-OUTPUT* unless SHOW-PROGRESS-P is NIL and returns a true
value iff all tests succeeded.  Errors in BODY are caught and reported
\(and counted as failures)."
  `(let ((successp t)
         (testcount 1))
     (block test-block
       (flet ((done ()
                (return-from test-block successp)))
         (format t "~&Test: ~A~%" ,name)
         (loop
          (when (and ,show-progress-p (zerop (mod testcount 10)))
            (format t ".")
            (when (zerop (mod testcount 100))
              (terpri))
            (force-output))
          (let ((errors
                 (handler-case
                     (progn ,@body)
                   (error (msg)
                     (list (format nil "~&got an unexpected error: ~A" msg))))))
            (setq successp (and successp (null errors)))
            (when errors
              (format t "~&~4@A:~{~&   ~A~}~%" testcount errors))
            (incf testcount)))))
     successp))

(defun simple-tests (&key (file-name
                           (make-pathname :name "simple"
                                          :type nil :version nil
                                          :defaults *this-file*))
                          (external-format '(:latin-1 :eol-style :lf))
                          verbose)
  "Loops through all the forms in the file FILE-NAME and executes each
of them using EVAL.  It is assumed that each FORM specifies a test which
returns a true value iff it succeeds.  Prints each test form to
*STANDARD-OUTPUT* if VERBOSE is true and shows a simple progress indicator
otherwise.  EXTERNAL-FORMAT is the external format which is used to read the
file.  Returns a true value iff all tests succeeded."
  (with-open-file (stream file-name :element-type 'std:octet :external-format external-format)
    (let ((*package* (find-package :std/tests)))
      (%do-tests ((format nil "Simple tests from file ~S" (file-namestring file-name))
                 (not verbose))
        (let ((form (or (read stream nil) (done))))
          (when verbose
            (format t "~&~S" form))
          (cond ((eval form) nil)
                (t (list (format nil "~S returned NIL" form)))))))))

(defun random-test-function (probability)
  "Returns a random character test function which contains each
character with probability PROBABILITY."
  (let ((hash-table (make-hash-table)))
    (dotimes (code char-code-limit)
      (let ((char (code-char code)))
        (when (and char (< (random 1.0d0) probability))
          (setf (gethash (code-char code) hash-table) t))))
    (lambda (char)
      (gethash char hash-table))))

(defun test-optimized-test-functions% (probability)
  "Creates a random test function with probability PROBABILITY and six
\(one for each possible \"kind\") corresponding optimized test
functions, then checks for each character in turn that all functions
agree on it."
  (let* ((test-function (random-test-function probability))
         (optimized-functions (loop for kind in '(nil
                                                  :hash-table
                                                  :hash-table*
                                                  :charset
                                                  :charset*
                                                  :charmap)
                                    collect (create-optimized-test-function test-function :kind kind))))
    (loop for code below char-code-limit
          for char = (code-char code)
          for expected-result = (and char (funcall test-function char))
          always (or (null char)
                     (loop for optimized-function in optimized-functions
                           always (eq (not (funcall optimized-function char))
                                      (not expected-result)))))))

(defun test-optimized-test-functions (&key verbose)
  "Runs TEST-OPTIMIZED-TEST-FUNCTIONS% with different probabilities."
  (let ((probabilities '(0 .001 .01 .1 1)))
    (%do-tests ("Optimized test functions - this might take some time..." (not verbose))
      (let ((probability (or (pop probabilities) (done))))
        (when verbose
          (format t "~&Probability is ~A" probability))
        (not (test-optimized-test-functions% probability))))))

(defun run-all-ppcre-tests (&key more-tests verbose)
  "Runs all tests for PPCRE and returns a true value iff all tests
succeeded.  VERBOSE is interpreted by the individual test suites.
MORE-TESTS can be a list of function designators designating
additional tests to run."
  (let ((successp t))
    (macrolet ((run-test-suite (&body body)
                 `(unless (progn ,@body)
                    (setq successp nil))))
      ;; run the automatically generated Perl tests
      (run-test-suite (perl-test :verbose verbose))
      (run-test-suite (test-optimized-test-functions :verbose verbose))
      (run-test-suite (simple-tests :verbose verbose))
      (when more-tests
        (unless (listp more-tests)
          (setq more-tests (list more-tests))
          (dolist (test more-tests)
            (run-test-suite (funcall test :verbose verbose))))))
    (format t "~2&~:[Some tests failed~;All tests passed~]." successp)
    successp))

(defvar *tests-to-skip* '(636 638 662 790 1439)
  "Some tests we skip because the testdata is generated by a Perl
program and PPCRE differs from Perl for these tests - on purpose.")

(defun create-string-from-input (input)
  "Converts INPUT to a string which can be used in TEST below.  The
input file `testdata' encodes strings containing non-printable
characters as lists where those characters are represented by their
character code."
  (etypecase input
    ((or null string) input)
    (list (ppcre::string-list-to-simple-string
           (loop for element in input
                 if (stringp element)
                 collect element
                 else
                 collect (string (code-char element)))))))

(defun perl-test (&key (file-name 
                        (make-pathname :name "perltestdata"
                                       :type nil :version nil
                                       :defaults *this-file*)
                        file-name-provided-p)
                       (external-format '(:latin-1 :eol-style :lf))
                       verbose)
  "Loops through all test cases in FILE-NAME and prints a report if
VERBOSE is true.  EXTERNAL-FORMAT is the external format which is used to read
the file.  Returns a true value if all tests succeeded.

For the syntax of the tests in FILE-NAME refer to the source code of this
function and to the Perl script perltest.pl which generates such test files."
  (declare #.ppcre::*standard-optimize-settings*)
  (with-open-file (stream file-name :element-type 'octet :external-format external-format)
    (let (;; the standard Perl tests don't need full Unicode support
          (*regex-char-code-limit* (if file-name-provided-p *regex-char-code-limit* 256))
          ;; we need this for the standard test suite or otherwise we
          ;; might get stack overflows
          (*optimize-char-classes* (if file-name-provided-p *optimize-char-classes* :charmap))
          ;; we only check for correctness and don't care about speed
          ;; that match (but rather about space constraints of the
          ;; trial versions)
          (*use-bmh-matchers* (if file-name-provided-p *use-bmh-matchers* nil))
          ;; some tests in the Perl suite explicitly check for this
          (*allow-quoting* (if file-name-provided-p *allow-quoting* t)))
      (%do-tests ((format nil "Running tests in file ~S" (file-namestring file-name))
                 (not verbose))
        (let ((input-line (or (read stream nil) (done)))
              errors)
          (destructuring-bind (counter
                               info-string%
                               regex%
                               case-insensitive-mode
                               multi-line-mode
                               single-line-mode
                               extended-mode
                               target%
                               perl-error
                               expected-result%
                               expected-registers)
              input-line
            (destructuring-bind (info-string regex target expected-result)
                (mapcar 'create-string-from-input
                        (list info-string% regex% target% expected-result%))
              (setq expected-registers (mapcar 'create-string-from-input expected-registers))
              (unless (find counter *tests-to-skip* :test #'=)
                (when verbose
                  (format t "~&~4D: ~S" counter info-string))                  
                (block inner-test-block
                  (let ((scanner
                         (handler-bind ((error (lambda (condition)
                                                 (declare (ignore condition))
                                                 (when perl-error
                                                   ;; we expected an
                                                   ;; error, so we can
                                                   ;; signal success
                                                   (return-from inner-test-block)))))
                           (create-scanner regex
                                           :case-insensitive-mode case-insensitive-mode
                                           :multi-line-mode multi-line-mode
                                           :single-line-mode single-line-mode
                                           :extended-mode extended-mode))))
                    (multiple-value-bind (start end reg-starts reg-ends)                        
                        (scan scanner target)
                      (cond (perl-error
                             (push (format nil "expected an error but got a result.")
                                   errors))
                            (t
                             (when (not (eq start expected-result))
                               (if start
                                   (let ((result (subseq target start end)))
                                     (unless (string= result expected-result)
                                       (push (format nil "expected ~S but got ~S."
                                                     expected-result result)
                                             errors))
                                     (setq reg-starts (coerce reg-starts 'list)
                                           reg-ends (coerce reg-ends 'list))
                                     (loop for i from 0
                                        for expected-register in expected-registers
                                        for reg-start = (nth i reg-starts)
                                        for reg-end = (nth i reg-ends)
                                        for register = (if (and reg-start reg-end)
                                                           (subseq target reg-start reg-end)
                                                           nil)
                                        unless (string= expected-register register)
                                        do (push (format nil "\\~A: expected ~S but got ~S."
                                                         (1+ i) expected-register register)
                                                 errors)))
                                   (push (format nil "expected ~S but got ~S."
                                                 expected-result start)
                                         errors))))))
                    errors))))))))))
