("sys/types.h" "stdint.h" "keyutils.h")

( ;; ERROR_CODE
 (:integer +key-spec-thread-keyring+ "KEY_SPEC_THREAD_KEYRING" t t)
 (:integer +key-spec-process-keyring+ "KEY_SPEC_PROCESS_KEYRING" t t)
 (:integer +key-spec-session-keyring+ "KEY_SPEC_SESSION_KEYRING" t t)
 (:integer +key-spec-user-keyring+ "KEY_SPEC_USER_KEYRING" t t)
 (:integer +key-spec-user-session-keyring+ "KEY_SPEC_USER_SESSION_KEYRING" t t)
 (:integer +key-spec-group-keyring+ "KEY_SPEC_GROUP_KEYRING" t t)
 (:integer +key-spec-reqkey-auth-key+ "KEY_SPEC_REQKEY_AUTH_KEY" t t)
 (:integer +key-reqkey-defl-no-change+ "KEY_REQKEY_DEFL_NO_CHANGE" t t)
 (:integer +key-reqkey-defl-default+ "KEY_REQKEY_DEFL_DEFAULT" t t)
 (:integer +key-reqkey-defl-thread-keyring+ "KEY_REQKEY_DEFL_THREAD_KEYRING" t t)
 (:integer +key-reqkey-defl-process-keyring+ "KEY_REQKEY_DEFL_PROCESS_KEYRING" t t)
 (:integer +key-reqkey-defl-session-keyring+ "KEY_REQKEY_DEFL_SESSION_KEYRING" t t)
 (:integer +key-reqkey-defl-user-keyring+ "KEY_REQKEY_DEFL_USER_KEYRING" t t)
 (:integer +key-reqkey-defl-user-session-keyring+ "KEY_REQKEY_DEFL_USER_SESSION_KEYRING" t t)
 (:integer +key-reqkey-defl-group-keyring+ "KEY_REQKEY_DEFL_GROUP_KEYRING" t t)
 (:integer +key-pos-view+ "KEY_POS_VIEW" t t)
 (:integer +key-pos-read+ "KEY_POS_READ" t t)
 (:integer +key-pos-write+ "KEY_POS_WRITE" t t)
 (:integer +key-pos-search+ "KEY_POS_SEARCH" t t)
 (:integer +key-pos-link+ "KEY_POS_LINK" t t)
 (:integer +key-pos-setattr+ "KEY_POS_SETATTR" t t)
 (:integer +key-pos-all+ "KEY_POS_ALL" t t)
 (:integer +key-usr-view+ "KEY_USR_VIEW" t t)
 (:integer +key-usr-read+ "KEY_USR_READ" t t)
 (:integer +key-usr-write+ "KEY_USR_WRITE" t t)
 (:integer +key-usr-search+ "KEY_USR_SEARCH" t t)
 (:integer +key-usr-link+ "KEY_USR_LINK" t t)
 (:integer +key-usr-setattr+ "KEY_USR_SETATTR" t t)
 (:integer +key-usr-all+ "KEY_USR_ALL" t t)
 (:integer +key-grp-view+ "KEY_GRP_VIEW" t t)
 (:integer +key-grp-read+ "KEY_GRP_READ" t t)
 (:integer +key-grp-write+ "KEY_GRP_WRITE" t t)
 (:integer +key-grp-search+ "KEY_GRP_SEARCH" t t)
 (:integer +key-grp-link+ "KEY_GRP_LINK" t t)
 (:integer +key-grp-setattr+ "KEY_GRP_SETATTR" t t)
 (:integer +key-grp-all+ "KEY_GRP_ALL" t t)
                                  
 (:integer +key-oth-view+ "KEY_OTH_VIEW" t t)
 (:integer +key-oth-read+ "KEY_OTH_READ" t t)
 (:integer +key-oth-write+ "KEY_OTH_WRITE" t t)
 (:integer +key-oth-search+ "KEY_OTH_SEARCH" t t)
 (:integer +key-oth-link+ "KEY_OTH_LINK" t t)
 (:integer +key-oth-setattr+ "KEY_OTH_SETATTR" t t)
 (:integer +key-oth-all+ "KEY_OTH_ALL" t t)
 (:integer +keyctl-get-keyring-id+ "KEYCTL_GET_KEYRING_ID" t t)
 (:integer +keyctl-join-session-keyring+ "KEYCTL_JOIN_SESSION_KEYRING" t t)
 (:integer +keyctl-update+ "KEYCTL_UPDATE" t t)
 (:integer +keyctl-revoke+ "KEYCTL_REVOKE" t t)
 (:integer +keyctl-chown+ "KEYCTL_CHOWN" t t)
 (:integer +keyctl-setperm+ "KEYCTL_SETPERM" t t)
 (:integer +keyctl-describe+ "KEYCTL_DESCRIBE" t t)
 (:integer +keyctl-clear+ "KEYCTL_CLEAR" t t)
 (:integer +keyctl-link+ "KEYCTL_LINK" t t)
 (:integer +keyctl-unlink+ "KEYCTL_UNLINK" t t)
 (:integer +keyctl-search+ "KEYCTL_SEARCH" t t)
 (:integer +keyctl-read+ "KEYCTL_READ" t t)
 (:integer +keyctl-instantiate+ "KEYCTL_INSTANTIATE" t t)
 (:integer +keyctl-negate+ "KEYCTL_NEGATE" t t)
 (:integer +keyctl-set-reqkey-keyring+ "KEYCTL_SET_REQKEY_KEYRING" t t)
 (:integer +keyctl-set-timeout+ "KEYCTL_SET_TIMEOUT" t t)
 (:integer +keyctl-assume-authority+ "KEYCTL_ASSUME_AUTHORITY" t t)
 (:integer +keyctl-get-security+ "KEYCTL_GET_SECURITY" t t)
 (:integer +keyctl-session-to-parent+ "KEYCTL_SESSION_TO_PARENT" t t)
 (:integer +keyctl-reject+ "KEYCTL_REJECT" t t)
 (:integer +keyctl-instantiate-iov+ "KEYCTL_INSTANTIATE_IOV" t t)
 (:integer +keyctl-invalidate+ "KEYCTL_INVALIDATE" t t)
 (:integer +keyctl-get-persistent+ "KEYCTL_GET_PERSISTENT" t t)
 (:integer +keyctl-dh-compute+ "KEYCTL_DH_COMPUTE" t t)
 (:integer +keyctl-pkey-query+ "KEYCTL_PKEY_QUERY" t t)
 (:integer +keyctl-pkey-encrypt+ "KEYCTL_PKEY_ENCRYPT" t t)
 (:integer +keyctl-pkey-decrypt+ "KEYCTL_PKEY_DECRYPT" t t)
 (:integer +keyctl-pkey-sign+ "KEYCTL_PKEY_SIGN" t t)
 (:integer +keyctl-pkey-verify+ "KEYCTL_PKEY_VERIFY" t t)
 (:integer +keyctl-restrict-keyring+ "KEYCTL_RESTRICT_KEYRING" t t)
 (:integer +keyctl-move+ "KEYCTL_MOVE" t t)
 (:integer +keyctl-capabilities+ "KEYCTL_CAPABILITIES" t t)
 (:integer +keyctl-watch-key+ "KEYCTL_WATCH_KEY" t t)
 (:integer +keyctl-supports-encrypt+ "KEYCTL_SUPPORTS_ENCRYPT" t t)
 (:integer +keyctl-supports-decrypt+ "KEYCTL_SUPPORTS_DECRYPT" t t)
 (:integer +keyctl-supports-sign+ "KEYCTL_SUPPORTS_SIGN" t t)
 (:integer +keyctl-supports-verify+ "KEYCTL_SUPPORTS_VERIFY" t t)
 (:integer +keyctl-move-excl+ "KEYCTL_MOVE_EXCL" t t)
 (:integer +keyctl-caps0-capabilities+ "KEYCTL_CAPS0_CAPABILITIES" t t)
 (:integer +keyctl-caps0-persistent-keyrings+ "KEYCTL_CAPS0_PERSISTENT_KEYRINGS" t t)
 (:integer +keyctl-caps0-diffie-hellman+ "KEYCTL_CAPS0_DIFFIE_HELLMAN" t t)
 (:integer +keyctl-caps0-public-key+ "KEYCTL_CAPS0_PUBLIC_KEY" t t)
 (:integer +keyctl-caps0-big-key+ "KEYCTL_CAPS0_BIG_KEY" t t)
 (:integer +keyctl-caps0-invalidate+ "KEYCTL_CAPS0_INVALIDATE" t t)
 (:integer +keyctl-caps0-restrict-keyring+ "KEYCTL_CAPS0_RESTRICT_KEYRING" t t)
 (:integer +keyctl-caps0-move+ "KEYCTL_CAPS0_MOVE" t t)
 (:integer +keyctl-caps1-ns-keyring-name+ "KEYCTL_CAPS1_NS_KEYRING_NAME" t t)
 (:integer +keyctl-caps1-ns-key-tag+ "KEYCTL_CAPS1_NS_KEY_TAG" t t)
 (:integer +keyctl-caps1-notifications+ "KEYCTL_CAPS1_NOTIFICATIONS" t t)
 (:structure keyctl-dh-params ("struct keyctl_dh_params"
                               (key-serial-t priv "key_serial_t" "priv")
                               (key-serial-t prime "key_serial_t" "prime")
                               (key-serial-t base "key_serial_t" "base"))
             t t)
 (:structure keyctl-kdf-params ("struct keyctl_kdf_params"
                                (c-string hashname "char *" "hashname")
                                (c-string otherinfo "char *" "otherinfo")
                                (unsigned-int otherinfolen "uint32_t" "otherinfolen")
                                ((array unsigned-int 8) spare "uint32_t" "__spare[8]"))
             t t)
 (:structure keyctl-pkey-query ("struct keyctl_pkey_query"
                                (unsigned-int supported-ops "unsigned int" "supported_ops")
                                (unsigned-int key-size "unsigned int" "key_size")
                                (unsigned-short max-data-size "unsigned short" "max_data_size")
                                (unsigned-short max-sig-size "unsigned short" "max_sig_size")
                                (unsigned-short max-enc-size "unsigned short" "max_enc_size")
                                (unsigned-short max-dec-size "unsigned short" "max_dec_size")
                                ((array unsigned-int 10) spare "unsigned int" "__spare[10]"))
             t t))
