("stdint.h" "stdio.h" "stdarg.h" "xkbcommon/xkbcommon-names.h" "xkbcommon/xkbcommon-keysyms.h" "xkbcommon/xkbcommon.h" "xkbcommon/xkbregistry.h" "xkbcommon/xkbcommon-compose.h")
((:integer +xkb-keycode-invalid+ "XKB_KEYCODE_INVALID")
 (:integer +xkb-layout-invalid+ "XKB_LAYOUT_INVALID")
 (:integer +xkb-level-invalid+ "XKB_LEVEL_INVALID")
 (:integer +xkb-mod-invalid+ "XKB_MOD_INVALID")
 (:integer +xkb-led-invalid+ "XKB_LED_INVALID")
 (:integer +xkb-keycode-max+ "XKB_KEYCODE_MAX")
 (:integer +xkb-keysym-max+ "XKB_KEYSYM_MAX")
 (:integer +xkb-keymap-use-original-format+ "XKB_KEYMAP_USE_ORIGINAL_FORMAT"))
