("stdint.h" "stdio.h" "stdarg.h" "xkbcommon/xkbcommon-names.h" "xkbcommon/xkbcommon-keysyms.h" "xkbcommon/xkbcommon.h" "xkbcommon/xkbregistry.h" "xkbcommon/xkbcommon-compose.h")

((:integer xkb-keycode-invalid "XKB_KEYCODE_INVALID" nil t)
 (:integer xkb-layout-invalid "XKB_LAYOUT_INVALID" nil t)
 (:integer xkb-level-invalid "XKB_LEVEL_INVALID" nil t)
 (:integer xkb-mod-invalid "XKB_MOD_INVALID" nil t)
 (:integer xkb-led-invalid "XKB_LED_INVALID" nil t)
 (:integer xkb-keycode-max "XKB_KEYCODE_MAX" nil t)
 (:integer xkb-keysym-max "XKB_KEYSYM_MAX" nil t)
 (:enum xkb-keymap-format ((xkb-keymap-format-text-v1 "XKB_KEYMAP_FORMAT_TEXT_V1")))
 (:enum xkb-log-level ((xkb-log-level-critical "XKB_LOG_LEVEL_CRITICAL")
                       (xkb-log-level-error "XKB_LOG_LEVEL_ERROR")
                       (xkb-log-level-warning "XKB_LOG_LEVEL_WARNING")
                       (xkb-log-level-info "XKB_LOG_LEVEL_INFO")
                       (xkb-log-level-debug "XKB_LOG_LEVEL_DEBUG")) nil t)
 (:enum xkb-keymap-compile-flags ((xkb-keymap-compile-no-flags "XKB_KEYMAP_COMPILE_NO_FLAGS")) nil t)
 (:integer xkb-keymap-use-original-format "XKB_KEYMAP_USE_ORIGINAL_FORMAT" nil t)
 (:enum xkb-key-direction ((xkb-key-up "XKB_KEY_UP")
                           (xkb-key-down "XKB_KEY_DOWN")))
 (:enum xkb-state-component ((xkb-state-mods-depressed "XKB_STATE_MODS_DEPRESSED")
                             (xkb-state-mods-latched "XKB_STATE_MODS_LATCHED")
                             (xkb-state-mods-locked "XKB_STATE_MODS_LOCKED")
                             (xkb-state-mods-effective "XKB_STATE_MODS_EFFECTIVE")
                             (xkb-state-layout-depressed "XKB_STATE_LAYOUT_DEPRESSED")
                             (xkb-state-layout-latched "XKB_STATE_LAYOUT_LATCHED")
                             (xkb-state-layout-locked "XKB_STATE_LAYOUT_LOCKED")
                             (xkb-state-layout-effective "XKB_STATE_LAYOUT_EFFECTIVE")
                             (xkb-state-leds "XKB_STATE_LEDS")) nil t)
 (:enum xkb-state-match ((xkb-state-match-any "XKB_STATE_MATCH_ANY")
                         (xkb-state-match-all "XKB_STATE_MATCH_ALL")
                         (xkb-state-match-non-exclusive "XKB_STATE_MATCH_NON_EXCLUSIVE")) nil t)
 (:enum xkb-consumed-mode ((xkb-consumed-mode-xkb "XKB_CONSUMED_MODE_XKB")
                           (xkb-consumed-mode-gtk "XKB_CONSUMED_MODE_GTK")) nil t)
 (:enum xkb-keysym-flags ((xkb-keysym-no-flags "XKB_KEYSYM_NO_FLAGS")
                          (xkb-keysym-case-insensitive "XKB_KEYSYM_CASE_INSENSITIVE")) nil t))
