("/opt/cuda/include/cuda.h" "/usr/include/cudnn_version.h")
                            
((:integer +cuda-version+ "CUDA_VERSION" nil t)
 (:integer +cu-ipc-handle-size+ "CU_IPC_HANDLE_SIZE" nil t)
 (:integer +cu-compute-accelerated-target-base+ "CU_COMPUTE_ACCELERATED_TARGET_BASE" nil t)
 (:integer +cu-graph-cond-assign-default+ "CU_GRAPH_COND_ASSIGN_DEFAULT" nil t)
 (:integer +cu-graph-kernel-node-port-default+ "CU_GRAPH_KERNEL_NODE_PORT_DEFAULT" nil t)
 (:integer +cu-graph-kernel-node-port-launch-order+ "CU_GRAPH_KERNEL_NODE_PORT_LAUNCH_ORDER" nil t)
 (:integer +cu-graph-kernel-node-port-programmatic+ "CU_GRAPH_KERNEL_NODE_PORT_PROGRAMMATIC" nil t)
 (:integer +cu-memhostalloc-portable+ "CU_MEMHOSTALLOC_PORTABLE" nil t)
 (:integer +cu-memhostalloc-devicemap+ "CU_MEMHOSTALLOC_DEVICEMAP" nil t)
 (:integer +cu-memhostalloc-writecombined+ "CU_MEMHOSTALLOC_WRITECOMBINED" nil t)
 (:integer +cu-memhostregister-portable+ "CU_MEMHOSTREGISTER_PORTABLE" nil t)
 (:integer +cu-memhostregister-devicemap+ "CU_MEMHOSTREGISTER_DEVICEMAP" nil t)
 (:integer +cu-memhostregister-iomemory+ "CU_MEMHOSTREGISTER_IOMEMORY" nil t)
 (:integer +cu-memhostregister-read-only+ "CU_MEMHOSTREGISTER_READ_ONLY" nil t)
 (:integer +cu-array-sparse-properties-single-miptail+ "CU_ARRAY_SPARSE_PROPERTIES_SINGLE_MIPTAIL" nil t)
 (:integer +cu-tensor-map-num-qwords+ "CU_TENSOR_MAP_NUM_QWORDS" nil t)
 (:integer +cudnn-major+ "CUDNN_MAJOR" nil t)
 (:integer +cudnn-minor+ "CUDNN_MINOR" nil t)
 (:integer +cudnn-patchlevel+ "CUDNN_PATCHLEVEL" nil t)
 (:integer +cudnn-version+ "CUDNN_VERSION" nil t)
 (:integer +cudnn-max-sm-major-number+ "CUDNN_MAX_SM_MAJOR_NUMBER" nil t)
 (:integer +cudnn-max-sm-minor-number+ "CUDNN_MAX_SM_MINOR_NUMBER" nil t)
 (:integer +cudnn-max-device-version+ "CUDNN_MAX_DEVICE_VERSION" nil t))

