[package]
name = "ui"
version.workspace = true
authors.workspace = true
edition.workspace = true
[[bin]]
name = "ui-base"
path = "main.rs"
[dependencies]
serde.workspace = true
slint = {version = "1.5.1", features = ["serde","software-renderer-systemfonts"]}

[build-dependencies]
slint-build = "1.5.1"
