(defpackage :zstd/tests 
    (:use :cl :rt :zstd))
(in-package :zstd/tests)
(defsuite :zstd)
(in-suite :zstd)
(load-zstd)
(deftest sanity ()
  (mapc (lambda (x)
          (is (= (car x) (cdr x))))
        `((,zstd::zstd-clevel-default . 3)
          (,zstd::zstd-magicnumber . -47205080)
          (,zstd::zstd-magic-skippable-start . 407710288)
          (,zstd::zstd-blocksizelog-max . 17)
          (,zstd::zstd-blocksize-max . 131072)
          (,zstd::zstd-contentsize-unknown . -1)
          (,zstd::zstd-contentsize-error . -2)
          (,zstd::zstd-max-input-size . -71777214294589696)
          (,zstd::zstd-version-number . 10506)
          (,zstd::zstd-magic-dictionary . -332356553))))
