;;; rocksdb/types.lisp --- Rocksdb FFI Types

;;

;;; Code:
(in-package :rocksdb)

(define-alien-type rocksdb-errptr (* (* t)))
(define-opaque rocksdb)
(define-opaque rocksdb-iterator)
(define-opaque rocksdb-backup-engine)
(define-opaque rocksdb-backup-engine-info)
(define-opaque rocksdb-memory-allocator)
(define-opaque rocksdb-cache)
(define-opaque rocksdb-compactionfilter)
(define-opaque rocksdb-compactionfiltercontext)
(define-opaque rocksdb-compactionfilterfactory)
(define-opaque rocksdb-file-checksum-gen-factory)
(define-opaque rocksdb-sst-partitioner-factory)
(define-opaque rocksdb-table-properties-collector-factory)
(define-opaque rocksdb-comparator)
(define-opaque rocksdb-dbpath)
(define-opaque rocksdb-env)
(define-opaque rocksdb-filelock)
(define-opaque rocksdb-filterpolicy)
(define-opaque rocksdb-logger)
(define-opaque rocksdb-mergeoperator)
(define-opaque rocksdb-randomfile)
(define-opaque rocksdb-seqfile)
(define-opaque rocksdb-slicetransform)
(define-opaque rocksdb-snapshot)
(define-opaque rocksdb-writeablefile)
(define-opaque rocksdb-writebatch)
(define-opaque rocksdb-writebatch-wi)
(define-opaque rocksdb-livefiles)
(define-opaque rocksdb-column-family-handle)
(define-opaque rocksdb-column-family-metadata)
(define-opaque rocksdb-level-metadata)
(define-opaque rocksdb-sst-file-manager)
(define-opaque rocksdb-sst-file-metadata)
(define-opaque rocksdb-sstfilewriter)
(define-opaque rocksdb-ratelimiter)
(define-opaque rocksdb-perfcontext)
(define-opaque rocksdb-pinnableslice)
(define-opaque rocksdb-pinnable-handle)
(define-opaque rocksdb-transactiondb)
(define-opaque rocksdb-optimistictransactiondb)
(define-opaque rocksdb-transaction)
(define-opaque rocksdb-checkpoint)
(define-opaque rocksdb-wal-iterator)
(define-opaque rocksdb-memory-consumers)
(define-opaque rocksdb-memory-usage)
(define-opaque rocksdb-statistics-histogram-data)
(define-opaque rocksdb-status-ptr)
(define-opaque rocksdb-flushjobinfo)
(define-opaque rocksdb-writestallcondition)
(define-opaque rocksdb-writestallinfo)
(define-opaque rocksdb-memtableinfo)
(define-opaque rocksdb-compactionservice)
(define-opaque rocksdb-compactionservice-scheduleresponse)
(define-opaque rocksdb-compactionservice-jobinfo)
(define-opaque rocksdb-compactionjobinfo)
(define-opaque rocksdb-subcompactionjobinfo)
(define-opaque rocksdb-externalfileingestioninfo)
(define-opaque rocksdb-eventlistener)
(define-opaque rocksdb-pinnable-multi-get)
(define-opaque rocksdb-export-import-files-metadata)
(define-opaque rocksdb-table-properties)
(define-alien-enum (rocksdb-size-approximation-flags)
  :none 0
  :include-memtable (ash 1 0)
  :include-files (ash 1 1)
  :include-blob-files (ash 1 2))
(define-alien-enum (rocksdb-compactionservice-jobstatus)
  :success 0
  :failure 1
  :aborted 2
  :use-local 3)

(define-alien-type rocksdb-slice
  (struct rocksdb-slice
    (data (* unsigned-char))
    (size size-t)))

(define-alien-type rocksdb-readoptions-table-filter-cb
    (function unsigned-char
        (* t)
        (* rocksdb-table-properties)))
