;;; autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from gen.el

(register-definition-prefixes "gen" '("gen-"))


;;; Generated autoloads from graph.el

(autoload 'org-graph-edge-convert-link "graph"
"Convert a normal `org-mode' link at `point' to a graph link, ARG prefix.
When called interactively with a `C-u' prefix argument do not modify
existing link.

(fn &optional ARG)" t)
(autoload 'org-graph-edge-delete "graph"
"Delete the link at point, and the corresponding backlink.
If no backlink exists, just delete link at point. This works from
either side, and deletes both sides of a link." t)
(autoload 'org-graph-edge-insert "graph"
"Insert an edge from `org-stored-links'." t)
(autoload 'org-graph-edge-link "graph"
"Insert a link edge and add a backlink edge to the target heading. With
'C-u' don't create a backlink to the target.

(fn &optional NO-BACKLINK)" t)
(autoload 'org-graph-node "graph"
"

(fn &optional ARG INVISIBLE-OK LEVEL)" t)
(autoload 'org-graph-kill-all "graph"
"

(fn &optional EXCLUDE-README)" t)
(autoload 'org-graph-init "graph"
"

(fn &optional NO-README)" t)
(autoload 'org-graph-load "graph"
"Load the org-graph from the org-graph-db." t)
(register-definition-prefixes "graph" '("graph-" "node-" "org-"))


;;; Generated autoloads from inbox.el

(register-definition-prefixes "inbox" '("org-" "with-inbox-buffer"))


;;; Generated autoloads from mpk.el

(register-definition-prefixes "mpk" '("mpk-"))


;;; Generated autoloads from org-expiry.el

(register-definition-prefixes "org-expiry" '("org-"))


;;; Generated autoloads from publish.el

(autoload 'update-sitemap "publish"
"Update compiler.company sitemaps." t)
(autoload 'publish "publish"
"publish `compiler.company' content.
If SITEMAP is t, generate sitemaps.
If FORCE is t, skip checking file mod date and just publish all files.
If ASYNC is t, call `org-publish' asynchronously.
If given a prefix (C-u), set all args to t

(fn &optional SITEMAP FORCE ASYNC)" t)
(register-definition-prefixes "publish" '("default-org-export-setupfile" "html-foot" "org-" "packy-url" "project-dir" "publish" "url" "vc-url" "with-org-publish"))


;;; Generated autoloads from scrum.el

(register-definition-prefixes "scrum" '("org-" "scrum-" "with-dblock-defaults"))


;;; Generated autoloads from skel.el

(register-definition-prefixes "skel" '("def-sk" "make-id" "maybe-skel-minor-mode" "organ-" "project" "read-skelfile-bind" "source" "target"))


;;; Generated autoloads from skt.el

(autoload 'skt-minor-mode "skt"
"Minor mode for skt-templates.

This is a minor mode.  If called interactively, toggle the `Skt minor
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `skt-minor-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

\\{skt-minor-mode-map}

(fn &optional ARG)" t)
(autoload 'skt--define "skt"
"Define a skt template.

DEFINE-FUNCTION is a function that takes a function symbol, BODY
and DOCSTRING as its arguments.  It must define a new function
with that symbol and that docstring.

NAME is a string used in generating a function symbol, TAG and
ABBREV.

MODES is a list of modes for which TAG and ABBREV will be
created.  If it's nil, TAG and ABBREV will be generated
globally.

TAG/ABBREV is a boolean, which indicates whether a tag/abbrev
must be created for this template.

DOCSTRING is a string (or nil) which will be supplied to
DEFINE-FUNCTION.

BODY is an arbitrary argument passed to DEFINE-FUNCTION.

(fn DEFINE-FUNCTION NAME MODES TAG ABBREV DOCSTRING BODY)")
(autoload 'skt-define-template "skt"
"Define a tempo template.

This macro defines a new tempo template or updates the old one.
NAME is a symbol.  ARGS is a list of the form ([KEY VALUE]...)
where each KEY can be one of :tag, :abbrev, :docstring or :mode.

If KEY is :tag, VALUE should be a boolean.  If VALUE is non-nil,
then a tempo tag with NAME will be created for this template.

If KEY is :abbrev, VALUE should be a boolean.  If VALUE is
non-nil, then a NAME abbrev will be created for this template.

If KEY is :docstring, VALUE should be a string.  It will be a
docstring of the generated function.

If KEY is :mode, VALUE should be a list of modes or single mode.
If this option is provided, than a tempo tag and an abbrev will
be created for these modes, otherwise they will be global (if
:tag and :abbrev options were provided, of course).

BODY is a sequence of tempo elements that will be passed as a
list directly to `tempo-define-template's second argument.

Example:
(skt-define-template defvar (:mode emacs-lisp-mode :tag t :abbrev t
                             :docstring \"defvar template\")
  \"(defvar \" (string-trim-right (buffer-name) (rx \".el\" eos)) \"-\" p n>
  r> \")\")

(fn NAME (&key MODE TAG ABBREV DOCSTRING) &body BODY)" nil t)
(autoload 'skt-define-skeleton "skt"
"Define skeleton template.
See `skt-define-template' for explanation of NAME, MODE, TAG,
ABBREV and DOCSTRING.

BODY is a sequence of skeleton elements that will be passed
directly to `define-skeleton'.

Example:
(skt-define-skeleton defun (:mode (emacs-lisp-mode lisp-interaction-mode)
                               :tag t :abbrev t
                               :docstring \"defun template\")
  \"(defun \" str \" (\" @ - \")\" 

  @ _ \")\" 
)

(fn NAME (&key MODE TAG ABBREV DOCSTRING) &rest BODY)" nil t)
(autoload 'skt-define-function "skt"
"Define FUNCTION template.
See `skt-define-template' for explanation of NAME, MODE, TAG,
ABBREV and DOCSTRING.

The main purpose of this macro, is to create tempo tags and
abbrevs for existing skeleton templates, such as `sh-case'.

Example:
(skt-define-function shcase (:tag t :abbrev t :mode `sh-mode') `sh-case')

(fn NAME (&key MODE TAG ABBREV DOCSTRING) FUNCTION)" nil t)
(autoload 'skt--complete-template "skt"
"An :override advice function for `tempo-display-completions'.
Show completion for STRING in a TAG-LIST.  After selection
expand template.

Rewritten because the original function uses an old way of
displaying completions in a separate buffer, which is not
clickable anyway.  Now it uses new (compared to the originial
tempo package) and shiny `completing-read' interface.

(fn STRING TAG-LIST)")
(defvar skt-enable-tempo-elements nil
"Enable extra tempo elements.
These elements add conditionals and looping support for tempo
like those in skeleton, making skeleton pretty much obsolete.

If you want to set this option from ELisp, you have to remove
`skt-tempo-user-elements' from `tempo-user-elements' on nil
and add it on non-nil.")
(custom-autoload 'skt-enable-tempo-elements "skt" nil)
(register-definition-prefixes "skt" '("skt-"))


;;; Generated autoloads from ulang.el

(autoload 'org-id-add-to-headlines-in-file "ulang"
"Add ID properties to all headlines in the
   current file which do not already have one." t)
(register-definition-prefixes "ulang" '("ol-vc-expand" "org-" "ulang-"))

;;; End of scraped data

(provide 'autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; autoloads.el ends here
