[workspace]
resolver = "2"
members = ["sys/btrfs",
           "sys/btrfsutil",
           "lib/util",
           "lib/flate",
           "lib/hash",
           "lib/net",
           "lib/dl",
           "lib/obj",
           "lib/audio",
           "lib/logger",
           "lib/db",
           "lib/sxp",
           "lib/tenex",
           "lib/crypto",
           "lib/krypt",
           "app/cli/cc-install",
           "app/cli/tz",
           "app/cli/mailman",
           "app/cli/krypt",
           "app/cli/alik",
           "app/cli/nu_plugin_rocksdb"]

[profile.release]
lto = true
panic = "abort"