[workspace]
resolver = "2"
members = ["lib/*","bin/*","ui/*", "ui/alik/dash"]
[workspace.package]
version = "0.1.0"
authors = ["Richard Westhaver <ellis@rwest.io>"]
edition = "2021"
[profile.release]
lto = true
panic = "abort"
[workspace.dependencies]
tokio = "1.37"
tokio-util = "0.7.10"
tokio-stream = "0.1.15"
serde = "1.0.200"
log = "0.4.21"
bindgen = "0.66.1"

# [profile.dev.package."*"]
# opt-level = 2

[patch.crates-io]
egui = { git = "https://github.com/emilk/egui", branch = "emilk/release-0.27.2" }
eframe = { git = "https://github.com/emilk/egui", branch = "emilk/release-0.27.2" }
