("sys/epoll.h")
((:integer epoll-cloexec "EPOLL_CLOEXEC")
 (:integer epoll-ctl-add "EPOLL_CTL_ADD")
 (:integer epoll-ctl-del "EPOLL_CTL_DEL")
 (:integer epoll-ctl-mod "EPOLL_CTL_MOD")
 (:integer epollin "EPOLLIN")
 (:integer epollrdnorm "EPOLLRDNORM")
 (:integer epollrdband "EPOLLRDBAND")
 (:integer epollpri "EPOLLPRI")
 (:integer epollout "EPOLLOUT")
 (:integer epollwrnorm "EPOLLWRNORM")
 (:integer epollwrband "EPOLLWRBAND")
 (:integer epollerr "EPOLLERR")
 (:integer epollhup "EPOLLHUP")
 (:integer epollmsg "EPOLLMSG")
 (:integer epolloneshot "EPOLLONESHOT")
 (:integer epollet "EPOLLET"))

