;;; autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from default.el

(register-definition-prefixes "default" '("add-to-load-path" "darwin-p" "flatten" "gen-" "group" "hash-table-alist" "intersperse" "join-paths" "linux-p" "load-" "mkstr" "symb" "upgrade-emacs"))


;;; Generated autoloads from gen.el

(autoload 'maybe-enable-gen-minor-mode "gen")
(register-definition-prefixes "gen" '("gen-"))


;;; Generated autoloads from graph.el

(autoload 'org-graph-edge-convert-link "graph"
"Convert a normal `org-mode' link at `point' to a graph link, ARG prefix.
When called interactively with a `C-u' prefix argument do not modify
existing link.

(fn &optional ARG)" t)
(autoload 'org-graph-edge-delete "graph"
"Delete the link at point, and the corresponding backlink.
If no backlink exists, just delete link at point. This works from
either side, and deletes both sides of a link." t)
(autoload 'org-graph-edge-insert "graph"
"Insert an edge from `org-stored-links'." t)
(autoload 'org-graph-edge-link "graph"
"Insert a link edge and add a backlink edge to the target heading. With
'C-u' don't create a backlink to the target.

(fn &optional NO-BACKLINK)" t)
(autoload 'org-graph-node "graph"
"

(fn &optional ARG INVISIBLE-OK LEVEL)" t)
(autoload 'org-graph-kill-all "graph"
"

(fn &optional EXCLUDE-README)" t)
(autoload 'org-graph-init "graph"
"

(fn &optional NO-README)" t)
(autoload 'org-graph-load "graph"
"Load the org-graph from the org-graph-db." t)
(autoload 'org-graph-save "graph"
"Save the org-graph to a sxp file.

(fn &optional OUTPUT JSON)" t)
(register-definition-prefixes "graph" '("graph-" "node-" "org-"))


;;; Generated autoloads from inbox.el

(autoload 'org-inbox-init "inbox")
(register-definition-prefixes "inbox" '("org-" "with-inbox-buffer"))


;;; Generated autoloads from keymaps.el

(register-definition-prefixes "keymaps" '("clock-map" "parens-map" "review-map" "status-map" "toggle-map" "user-map"))


;;; Generated autoloads from mpk.el

(register-definition-prefixes "mpk" '("mpk-"))


;;; Generated autoloads from org-expire.el

(register-definition-prefixes "org-expire" '("org-"))


;;; Generated autoloads from organ.el

(autoload 'org-id-add-to-headlines-in-file "organ"
"Add ID properties to all headlines in the
   current file which do not already have one." t)
(register-definition-prefixes "organ" '("extract-org-directory-titles-as-list" "get-html-title-from-url" "include-directory-org-files" "insert-directory-org-file" "org-" "region-to-clocked-task"))


;;; Generated autoloads from plan.el

(register-definition-prefixes "plan" '("org-" "plan-" "with-dblock-defaults"))


;;; Generated autoloads from publish.el

(autoload 'update-sitemap "publish"
"Update compiler.company sitemaps." t)
(autoload 'publish "publish"
"publish `compiler.company' content.
If SITEMAP is t, generate sitemaps.
If FORCE is t, skip checking file mod date and just publish all files.
If ASYNC is t, call `org-publish' asynchronously.
If given a prefix (C-u), set all args to t

(fn &optional SITEMAP FORCE ASYNC)" t)
(register-definition-prefixes "publish" '("default-org-export-setupfile" "html-foot" "org-" "packy-url" "project-dir" "publish" "url" "vc-url" "with-org-publish"))


;;; Generated autoloads from scratch.el

(autoload 'default-scratch-buffer "scratch"
"Produce a bespoke scratch buffer matching current major mode.

With optional ARG as a prefix argument (\\[universal-argument]),
use `default-scratch-buffer-mode'.

With ARG as a double prefix argument, prompt for a major mode
with completion.

If region is active, copy its contents to the new scratch
buffer.

(fn &optional ARG)" t)
(autoload 'scratch-new "scratch"
"create a new scratch buffer. (could be *scratch* - *scratchN*)" t)
(register-definition-prefixes "scratch" '("default-scratch-"))


;;; Generated autoloads from site-start.el

(register-definition-prefixes "site-start" '("company-" "core-lisp-program" "default-theme" "emacs-config-source" "site-lisp-directory" "source-directory" "user-"))


;;; Generated autoloads from skel.el

(autoload 'init-skel "skel")
(register-definition-prefixes "skel" '("def-skel-cmd" "make-id" "organ-" "project-" "read-skelfile-bind" "run-skel-shell" "skel-"))


;;; Generated autoloads from skt.el

(autoload 'skt-minor-mode "skt"
"Minor mode for skt-templates.

This is a minor mode.  If called interactively, toggle the `Skt minor
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `skt-minor-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'skt--define "skt"
"Define a skt template.

DEFINE-FUNCTION is a function that takes a function symbol, BODY
and DOCSTRING as its arguments.  It must define a new function
with that symbol and that docstring.

NAME is a string used in generating a function symbol, TAG and
ABBREV.

MODES is a list of modes for which TAG and ABBREV will be
created.  If it's nil, TAG and ABBREV will be generated
globally.

TAG/ABBREV is a boolean, which indicates whether a tag/abbrev
must be created for this template.

DOCSTRING is a string (or nil) which will be supplied to
DEFINE-FUNCTION.

BODY is an arbitrary argument passed to DEFINE-FUNCTION.

(fn DEFINE-FUNCTION NAME MODES TAG ABBREV DOCSTRING BODY)")
(autoload 'skt-define-template "skt"
"Define a tempo template.

This macro defines a new tempo template or updates the old one.
NAME is a symbol.  ARGS is a list of the form ([KEY VALUE]...)
where each KEY can be one of :tag, :abbrev, :docstring or :mode.

If KEY is :tag, VALUE should be a boolean.  If VALUE is non-nil,
then a tempo tag with NAME will be created for this template.

If KEY is :abbrev, VALUE should be a boolean.  If VALUE is
non-nil, then a NAME abbrev will be created for this template.

If KEY is :docstring, VALUE should be a string.  It will be a
docstring of the generated function.

If KEY is :mode, VALUE should be a list of modes or single mode.
If this option is provided, than a tempo tag and an abbrev will
be created for these modes, otherwise they will be global (if
:tag and :abbrev options were provided, of course).

BODY is a sequence of tempo elements that will be passed as a
list directly to `tempo-define-template's second argument.

Example:
(skt-define-template defvar (:mode emacs-lisp-mode :tag t :abbrev t
                             :docstring \"defvar template\")
  \"(defvar \" (string-trim-right (buffer-name) (rx \".el\" eos)) \"-\" p n>
  r> \")\")

(fn NAME (&key MODE TAG ABBREV DOCSTRING) &body BODY)" nil t)
(autoload 'skt-define-skeleton "skt"
"Define skeleton template.
See `skt-define-template' for explanation of NAME, MODE, TAG,
ABBREV and DOCSTRING.

BODY is a sequence of skeleton elements that will be passed
directly to `define-skeleton'.

Example:
(skt-define-skeleton defun (:mode (emacs-lisp-mode lisp-interaction-mode)
                               :tag t :abbrev t
                               :docstring \"defun template\")
  \"(defun \" str \" (\" @ - \")\" 

  @ _ \")\" 
)

(fn NAME (&key MODE TAG ABBREV DOCSTRING) &rest BODY)" nil t)
(autoload 'skt-define-function "skt"
"Define FUNCTION template.
See `skt-define-template' for explanation of NAME, MODE, TAG,
ABBREV and DOCSTRING.

The main purpose of this macro, is to create tempo tags and
abbrevs for existing skeleton templates, such as `sh-case'.

Example:
(skt-define-function shcase (:tag t :abbrev t :mode `sh-mode') `sh-case')

(fn NAME (&key MODE TAG ABBREV DOCSTRING) FUNCTION)" nil t)
(autoload 'skt--complete-template "skt"
"An :override advice function for `tempo-display-completions'.
Show completion for STRING in a TAG-LIST.  After selection
expand template.

Rewritten because the original function uses an old way of
displaying completions in a separate buffer, which is not
clickable anyway.  Now it uses new (compared to the originial
tempo package) and shiny `completing-read' interface.

(fn STRING TAG-LIST)")
(defvar skt-enable-tempo-elements nil
"Enable extra tempo elements.
These elements add conditionals and looping support for tempo
like those in skeleton, making skeleton pretty much obsolete.

If you want to set this option from ELisp, you have to remove
`skt-tempo-user-elements' from `tempo-user-elements' on nil
and add it on non-nil.")
(custom-autoload 'skt-enable-tempo-elements "skt" nil)
(register-definition-prefixes "skt" '("skt-"))


;;; Generated autoloads from slime/slime.el

(autoload 'slime-setup "slime"
"Setup Emacs so that lisp-mode buffers always use SLIME.
CONTRIBS is a list of contrib packages to load. If `nil', use
`slime-contribs'. 

(fn &optional (CONTRIBS nil CONTRIBS-P))" t)
(autoload 'slime-mode "slime"
"\\<slime-mode-map>SLIME: The Superior Lisp Interaction Mode for Emacs (minor-mode).

Commands to compile the current buffer's source file and visually
highlight any resulting compiler notes and warnings:
\\[slime-compile-and-load-file]	- Compile and load the current buffer's file.
\\[slime-compile-file]	- Compile (but not load) the current buffer's file.
\\[slime-compile-defun]	- Compile the top-level form at point.

Commands for visiting compiler notes:
\\[slime-next-note]	- Goto the next form with a compiler note.
\\[slime-previous-note]	- Goto the previous form with a compiler note.
\\[slime-remove-notes]	- Remove compiler-note annotations in buffer.

Finding definitions:
\\[slime-edit-definition]
- Edit the definition of the function called at point.
\\[slime-pop-find-definition-stack]
- Pop the definition stack to go back from a definition.

Documentation commands:
\\[slime-describe-symbol]	- Describe symbol.
\\[slime-apropos]	- Apropos search.
\\[slime-disassemble-symbol]	- Disassemble a function.

Evaluation commands:
\\[slime-eval-defun]	- Evaluate top-level from containing point.
\\[slime-eval-last-expression]	- Evaluate sexp before point.
\\[slime-pprint-eval-last-expression]	- Evaluate sexp before point, pretty-print result.

Full set of commands:
\\{slime-mode-map}

This is a minor mode.  If called interactively, toggle the `Slime mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `slime-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'slime "slime"
"Start an inferior^_superior Lisp and connect to its Swank server.

(fn &optional COMMAND CODING-SYSTEM)" t)
(autoload 'slime-connect "slime"
"Connect to a running Swank server. Return the connection.

(fn HOST PORT &optional CODING-SYSTEM INTERACTIVE-P &rest PARAMETERS)" t)
(autoload 'slime-selector "slime"
"Select a new buffer by type, indicated by a single character.
The user is prompted for a single character indicating the method by
which to choose a new buffer. The `?' character describes the
available methods.

See `def-slime-selector-method' for defining new methods.

(fn &optional OTHER-WINDOW)" t)
(register-definition-prefixes "slime" '("def-slime-selector-method" "define-sl" "defslimefun" "inferior-lisp-program" "make-slime-" "sldb-" "slime-" "topline"))


;;; Generated autoloads from slime/slime-autoloads.el

(register-definition-prefixes "slime-autoloads" '("slime-contribs"))


;;; Generated autoloads from slime/slime-tests.el

(register-definition-prefixes "slime-tests" '("arglist" "async-eval-debugging" "break" "comp" "def-slime-test" "dis" "end-of-file" "find-definition" "flow-control" "indentation" "inspector" "inter" "locally-bound-debugger-hook" "loop-interrupt-" "macroexpand" "narrowing" "read-from-minibuffer" "report-condition-with-circular-list" "sbcl-world-lock" "sexp-at-point." "symbol-at-point." "unwind-to-previous-sldb-level" "utf-8-source"))


;;; Generated autoloads from ulang.el

(autoload 'ulang-init "ulang" nil t)
(autoload 'prog-comment-dwim "ulang"
"Flexible, do-what-I-mean commenting.

If region is active and ARG is either a numeric argument greater
than one or a universal prefix (\\[universal-argument]), then
apply `comment-kill' on all comments in the region.

If the region is active and no ARG is supplied, or is equal to a
numeric prefix of 1, then toggle the comment status of the region.

Else toggle the comment status of the line at point.  With a
numeric prefix ARG, do so for ARGth lines (negative prefix
operates on the lines before point).

(fn ARG)" t)
(autoload 'prog-comment-timestamp-keyword "ulang"
"Add timestamped comment with KEYWORD.

When called interactively, the list of possible keywords is that
of `prog-comment-keywords', though it is possible to
input arbitrary text.

If point is at the beginning of the line or if line is empty (no
characters at all or just indentation), the comment is started
there in accordance with `comment-style'.  Any existing text
after the point will be pushed to a new line and will not be
turned into a comment.

If point is anywhere else on the line, the comment is indented
with `comment-indent'.

The comment is always formatted as 'DELIMITER KEYWORD DATE:',
with the date format being controlled by the variable
`prog-comment-timestamp-format-concise'.

With optional VERBOSE argument (such as a prefix argument
`\\[universal-argument]'), use an alternative date format, as
specified by `prog-comment-timestamp-format-verbose'.

(fn KEYWORD &optional VERBOSE)" t)
(register-definition-prefixes "ulang" '("default-line-regexp-" "first-day-of-week" "format-iso-week-number" "last-day-of-" "org-" "prog-comment-" "ulang-"))

;;; End of scraped data

(provide 'autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; autoloads.el ends here
