("stddef.h" "zstd_errors.h" "zstd.h" "zdict.h")
((:integer +zstd-version-major+ "ZSTD_VERSION_MAJOR" t t)
 (:integer +zstd-version-minor+ "ZSTD_VERSION_MINOR" t t)
 (:integer +zstd-version-release+ "ZSTD_VERSION_RELEASE" t t)
 (:integer +zstd-version-number+ "ZSTD_VERSION_NUMBER" t t)
 (:integer +zstd-clevel-default+ "ZSTD_CLEVEL_DEFAULT" t t)
 (:integer +zstd-magicnumber+ "ZSTD_MAGICNUMBER" t t)
 (:integer +zstd-magic-dictionary+ "ZSTD_MAGIC_DICTIONARY" t t)
 (:integer +zstd-magic-skippable-start+ "ZSTD_MAGIC_SKIPPABLE_START" t t)
 (:integer +zstd-blocksizelog-max+ "ZSTD_BLOCKSIZELOG_MAX" t t)
 (:integer +zstd-blocksize-max+ "ZSTD_BLOCKSIZE_MAX" t t)
 (:integer +zstd-contentsize-unknown+ "ZSTD_CONTENTSIZE_UNKNOWN" t t)
 (:integer +zstd-contentsize-error+ "ZSTD_CONTENTSIZE_ERROR" t t)
 (:integer +zstd-max-input-size+ "ZSTD_MAX_INPUT_SIZE" t t)
 (:structure zstd-inbuffer ("struct ZSTD_inBuffer_s"
                            ((* t) src "const void*" "src")
                            (size-t size "size_t" "size")
                            (size-t pos "size-t" "pos"))
             nil t)
 (:structure zstd-outbuffer ("struct ZSTD_outBuffer_s"
                             ((* t) dst "void*" "dst")
                             (size-t size "size_t" "size")
                             (size-t pos "size-t" "pos"))
             nil t))
