("stddef.h" "zstd_errors.h" "zstd.h" "zdict.h")
((:integer +zstd-version-major+ "ZSTD_VERSION_MAJOR")
 (:integer +zstd-version-minor+ "ZSTD_VERSION_MINOR")
 (:integer +zstd-version-release+ "ZSTD_VERSION_RELEASE")
 (:integer +zstd-version-number+ "ZSTD_VERSION_NUMBER")
 (:integer +zstd-clevel-default+ "ZSTD_CLEVEL_DEFAULT")
 (:integer +zstd-magicnumber+ "ZSTD_MAGICNUMBER")
 (:integer +zstd-magic-dictionary+ "ZSTD_MAGIC_DICTIONARY")
 (:integer +zstd-magic-skippable-start+ "ZSTD_MAGIC_SKIPPABLE_START")
 (:integer +zstd-blocksizelog-max+ "ZSTD_BLOCKSIZELOG_MAX")
 (:integer +zstd-blocksize-max+ "ZSTD_BLOCKSIZE_MAX")
 (:integer +zstd-contentsize-unknown+ "ZSTD_CONTENTSIZE_UNKNOWN")
 (:integer +zstd-contentsize-error+ "ZSTD_CONTENTSIZE_ERROR")
 (:integer +zstd-max-input-size+ "ZSTD_MAX_INPUT_SIZE")
 (:structure zstd-inbuffer ("struct ZSTD_inBuffer_s"
                            ((* t) src "const void*" "src")
                            (size-t size "size_t" "size")
                            (size-t pos "size-t" "pos")))
 (:structure zstd-outbuffer ("struct ZSTD_outBuffer_s"
                             ((* t) dst "void*" "dst")
                             (size-t size "size_t" "size")
                             (size-t pos "size-t" "pos"))))
