;;; rdb/proto.lisp --- RDB protocol

;; Extends OBJ/DB protocol with RocksDB-specific generics.

;;; Code:
(in-package :rdb)

;; Most methods are intended to work with the RDB struct directly
(defgeneric put-kv (self kv)
  (:documentation "Insert a KeyVal object."))
(defgeneric put-key (self key val)
  (:documentation "Insert a KEY and VAL."))
(defgeneric get-key (self key &key)
  (:documentation "Get value of KEY."))
(defgeneric multi-get (self keys &key)
  (:documentation "Retrieve multiple KEYS from SELF."))
(defgeneric get-opt (self key)
  (:documentation "Get value of option KEY."))
(defgeneric set-opt (self key val &key)
  (:documentation "Set value of option KEY to VAL."))
(defgeneric push-sap (self key))
(defgeneric push-sap* (self))
(defgeneric push-cf (self cf))
(defgeneric insert-key (self key val &key))
(defgeneric insert-kv (self kv &key))
(defgeneric make-kv (key val))
(defgeneric delete-key (self key val &key))
(defgeneric make-transaction (self &key))
(defgeneric commit-transaction (self &key))
(defgeneric flush-db (self &key))
(defgeneric flush-cf (self cf &key))
(defgeneric repair-db (self &key))
(defgeneric write-db (self batch &key))
(defgeneric make-val (val)
  (:method ((val null))
    #())
  (:method ((val string))
    (string-to-octets val))
  (:method ((val t))
    val))

(defgeneric make-key (key)
  (:method ((val null))
    #())
  (:method ((val string))
    (string-to-octets val))
  (:method ((val t))
    val))

(defgeneric merge-key (self key val &key))
(defgeneric merge-kv (self kv &key))
