;;; rdb/proto.lisp --- RDB protocol

;; Extends OBJ/DB protocol with RocksDB-specific generics.

;;; Code:
(in-package :rdb)

(defgeneric get-opt (self key)
  (:documentation "Get value of option KEY."))
(defgeneric set-opt (self key val &key)
  (:documentation "Set value of option KEY to VAL."))
(defgeneric push-opts (self)
  (:documentation "Push all options to internal sap."))
(defgeneric backfill-opts (self &key)
  (:documentation "Backfill opts from an alien."))
(defgeneric load-opts (self)
  (:documentation "Load existing database options. Assumes that the database has been opened and
flushed to disk at least once."))
(defgeneric push-sap (self key)
  (:documentation "Push a value associated with KEY to the sap associated
with SELF. Typically used to send a value from one slot, to a foreign
handle stored in another slot of the same object."))
(defgeneric push-sap* (self)
  (:documentation "Implicitly push values to the sap associated with SELF."))
(defgeneric pull-sap (self key)
  (:documentation "Pull a foreign value identified by KEY from the sap associated with SELF."))
(defgeneric pull-sap* (self)
  (:documentation "Implicitly pull foreign values from the sap associated with SELF."))
(defgeneric push-cf (cf self)
  (:documentation "Push a column-family to a sap."))
(defgeneric open-cfs (self &rest names)
  (:documentation "Open the column-families indicated by NAMES or all column-fmailies belonging
to SELF."))
(defgeneric close-cf (self &optional error)
  (:documentation "Close the column-family SELF. When ERROR is non-nil signal an error if the
column-family is already closed."))
(defgeneric close-cfs (self)
  (:documentation "Close the column-families belonging to SELF."))
(defgeneric find-cf (cf self &key)
  (:documentation "Find the column-familiy CF in SELF."))
(defgeneric flush-cf (self cf &key)
  (:documentation "Flush the column-family CF in SELF."))
(defgeneric get-prop (self propname)
  (:documentation "Get the property-value of PROPNAME from SELF."))
(defgeneric get-stats (self &optional htype)
  (:documentation "Get stats modulo HTYPE from SELF."))
(defgeneric print-stats (self &optional stream)
  (:documentation "Print statistics data from SELF."))
(defgeneric get-metadata (self &optional arg)
  (:documentation "Get metadata from SELF modulo ARG."))
(defgeneric create-iter (self &optional cf opts)
  (:documentation "Create an interator over the kvs of SELF module CF and OPTS."))
(defgeneric iter-next (self)
  (:documentation "Return the next value."))
(defgeneric iter-prev (self)
  (:documentation "Return the previous value."))
(defgeneric iter-seek (self key &key)
  (:documentation "Seek to a certain KEY in the iterator."))
(defgeneric iter-val (self)
  (:documentation "Return the value of current iterator item."))
(defgeneric iter-valid-p (self)
  (:documentation "Return non-nil if the iterator cursor is valid."))
(defgeneric iter-key (self)
  (:documentation "Return the key of current iterator item."))
(defgeneric iter-kv (self)
  (:documentation "Return the current KV object of the iterator by getting the key and
val."))
(defgeneric iter-timestamp (self)
  (:documentation "Return the timestamp of current iterator item."))

(defgeneric merge-key (self key val &key)
  (:documentation "Perform a merge operation on SELF using KEY and VAL."))

(defgeneric merge-kv (self kv &key)
  (:documentation "Perform a merge operation on SELF using object KV."))
