;;; qemu.lisp --- QEMU

;; QEMU support for Common Lisp

;;; Commentary:

;; For now we merely want to be able to configure, build and launch images.

;;; Code:
(in-package :box/qemu)

(defconfig qemu-img-config (box-config) 
  ((base)
   (format)
   (filename)
   (compression)
   (size)))

(defmethod make-config ((fmt (eql :qemu-img)) &rest args &key ast &allow-other-keys)
  (let ((cfg (apply 'make-instance 'qemu-img-config args)))
    (when ast (load-ast cfg))
    cfg))

(defconfig qemu-system-config (box-config)
  ((image)
   (machine)
   (accel)
   (vmport)
   (dump-guest-core)
   (mem-merge)
   (aes-key-wrap)
   (dea-key-wrap)
   (nvdimm)
   (memory-encryption)
   (hmat)
   (spcr)
   (aux-ram-share)
   (memory-backend)
   (cpu)
   (smp)
   (numa)
   (global)
   (boot)
   (mem)
   (mem-path)
   (mem-prealloc)
   (language)
   (audio)
   (audiodev)
   (device)
   (name)
   (uuid)
   ;; block
   (fda)
   (fdb)
   (hda)
   (hdb)
   (hdc)
   (hdd)
   (cdrom)
   (blockdev)
   (drive)
   (mtdblock)
   (sd)
   (snapshot)
   (fsdev)
   (virtfs)
   (iscsi)
   ;; usb
   (usb)
   (usbdevice)
   ;; display
   (display)
   (nographic)
   (spice)
   (vga)
   (full-screen)
   (vnc)
   ;; network
   (nic)
   (netdev)
   (net)
   ;; chardev
   (chardev)
   ;; tpm
   (tpmdev)
   ;; boot/kernel
   (bios)
   (pflash)
   (kernel)
   (shim)
   (append)
   (initrd)
   (dtb)
   ;; debug/expert
   (serial)
   (parallel)
   (monitor)
   (qmp)
   (qmp-pretty)
   (mon)
   (debugcon)
   (pidfile)
   (preconfig)
   (no-cpu-startup)
   (overcommit)
   (gdb)
   (log)
   (logfile)
   (seed)
   (enable-kvm)
   (no-reboot)
   (no-shutdown)
   (loadvm)
   (daemonize)
   (rtc)
   (option-rom)
   (icount)
   (echr)
   (nodefaults)
   (semihosting)
   (sandbox)
   (no-user-config)
   (trace)
   (plugin)
   (run-with)
   (msg)
   (dump-vmstate)
   (enable-sync-profile)
   (perfmap)
   (objects)))

(defmethod make-config ((fmt (eql :qemu)) &rest args &key ast &allow-other-keys)
  (let ((cfg (apply 'make-instance 'qemu-system-config args)))
    (when ast (load-ast cfg))
    cfg))
