:name "core/emacs"
:version "0.1.0"
:bind 
((dotemacs (merge-pathnames ".config/emacs/" (user-homedir-pathname)))
 (config (directory "emacs/*.el"))
 (lib (directory "emacs/lib/*.el")))
:rules 
((install ()
  (flet ((el-write (in out)
          (let* ((fn (file-namestring in)))
           (println (format nil "~A -> ~A" fn out))
           (std:with-open-files
            ((in in :direction :input)
             (out out :direction :output :if-exists :supersede))
            (std:copy-stream in out :finish-output t)))))
   (let ((dotemacs (merge-pathnames ".config/emacs/" (user-homedir-pathname)))
         (config (directory "*.el"))
         (lib (directory "lib/*.el")))
    (mapcar
     (lambda (el)
      (el-write el (merge-pathnames (file-namestring el) dotemacs)))
     config)
    (mapcar
     (lambda (el)
      (el-write el 
       (merge-pathnames (file-namestring el)
        (ensure-directories-exist 
         (merge-pathnames "lib/" dotemacs)))))
     lib))))
 (purge () 
  #$rm -rf $XDG_CONFIG_HOME/emacs/{*.el,lisp,site-lisp,lib,elpa,auto-save*,.cache,eln-cache,ielm-history.eld,tramp,transient,eshell,newsticker,emms,network-security.data,TAGS}$#))

