[package]
name = "krypt"
version = "0.1.0"
edition = "2021"
[dependencies]
crypto = { path = "../crypto" }
hash = { path = "../hash" }
obj = { path = "../obj", features = ["oauth"] }
# sxp = { path = "../sxp" }
keyutils = "0.4"
zeroize = "1.8"
secret-service = { version = "3.1.0", features = ["rt-tokio-crypto-rust"] }
serde = { version = "1.0.217", features = ["derive"] }
log = "0.4.25"
