(in-package :packy)
(defclass abstract-package (id) ())

(defgeneric pk-pack (self &key &allow-other-keys))
(defgeneric pk-unpack (self &key &allow-other-keys))
(defgeneric pk-install (self &key &allow-other-keys))
(defgeneric pk-uninstall (self &key &allow-other-keys))
(defgeneric pk-update (self &key &allow-other-keys))
(defgeneric pk-push (self &key &allow-other-keys))
(defgeneric pk-pull (self &key &allow-other-keys))
(defgeneric pk-query (self &key &allow-other-keys))
(defgeneric pk-sync (self &key &allow-other-keys))
(defgeneric pk-build (self &key &allow-other-keys))
