("signal.h" "errno.h" "sys/stat.h" "sys/syscall.h" "sys/epoll.h" "sys/syslog.h" "fcntl.h")

(;; signals
 ;; (:integer sig-ign "SIG_IGN") 1
 ;; (:long sig-dfl "SIG_DFL") 0
 (:integer sa-nocldstop "SA_NOCLDSTOP")
 (:integer sa-nocldwait "SA_NOCLDWAIT")
 (:integer sa-nodefer "SA_NODEFER")
 (:integer sa-onstack "SA_ONSTACK")
 (:integer sa-resethand "SA_RESETHAND")
 (:integer sa-restart "SA_RESTART")
 (:integer sa-siginfo "SA_SIGINFO")
 ;; fcntl
 (:integer o-cloexec "O_CLOEXEC")
 ;; stat
 (:integer s-irwxu "S_IRWXU")
 (:integer s-irusr "S_IRUSR")
 (:integer s-iwusr "S_IWUSR")
 (:integer s-ixusr "S_IXUSR")
 (:integer s-ififo "S_IFIFO")
 (:integer s-ifchr "S_IFCHR")
 (:integer s-ifblk "S_IFBLK")
 (:integer s-iread "S_IREAD")
 (:integer s-iwrite "S_IWRITE")
 (:integer s-iexec "S_IEXEC")
 (:integer s-irwxg "S_IRWXG")
 (:integer s-irgrp "S_IRGRP")
 (:integer s-iwgrp "S_IWGRP")
 (:integer s-ixgrp "S_IXGRP")
 (:integer s-irwxo "S_IRWXO")
 (:integer s-iroth "S_IROTH")
 (:integer s-iwoth "S_IWOTH")
 (:integer s-ixoth "S_IXOTH")
 (:integer s-isuid "S_ISUID")
 (:integer s-isgid "S_ISGID")
 (:integer s-isvtx "S_ISVTX")
 (:integer s-ifsock "S_IFSOCK")
 ;; errno
 (:integer ecanceled "ECANCELED")
 (:integer enotsup "ENOTSUP")
 ;; (:integer ebug "EBUG")
 ;; syscalls
 (:integer +sys-gettid+ "SYS_gettid")
 (:integer +sys-bpf+ "SYS_bpf")
 ;; epoll
 (:integer epoll-cloexec "EPOLL_CLOEXEC")
 (:integer epoll-ctl-add "EPOLL_CTL_ADD")
 (:integer epoll-ctl-del "EPOLL_CTL_DEL")
 (:integer epoll-ctl-mod "EPOLL_CTL_MOD")
 (:integer epollin "EPOLLIN")
 (:integer epollrdnorm "EPOLLRDNORM")
 (:integer epollrdband "EPOLLRDBAND")
 (:integer epollpri "EPOLLPRI")
 (:integer epollout "EPOLLOUT")
 (:integer epollwrnorm "EPOLLWRNORM")
 (:integer epollwrband "EPOLLWRBAND")
 (:integer epollerr "EPOLLERR")
 (:integer epollhup "EPOLLHUP")
 (:integer epollmsg "EPOLLMSG")
 (:integer epolloneshot "EPOLLONESHOT")
 (:integer epollet "EPOLLET")
 ;; syslog
 (:integer +log-emerg+ "LOG_EMERG")
 (:integer +log-alert+ "LOG_ALERT")
 (:integer +log-crit+ "LOG_CRIT")
 (:integer +log-err+ "LOG_ERR")
 (:integer +log-warning+ "LOG_WARNING")
 (:integer +log-notice+ "LOG_NOTICE")
 (:integer +log-info+ "LOG_INFO")
 (:integer +log-debug+ "LOG_DEBUG")
 (:integer +log-primask+ "LOG_PRIMASK")
 (:integer +log-kern+ "LOG_KERN")
 (:integer +log-user+ "LOG_USER")
 (:integer +log-mail+ "LOG_MAIL")
 (:integer +log-daemon+ "LOG_DAEMON")
 (:integer +log-auth+ "LOG_AUTH")
 (:integer +log-syslog+ "LOG_SYSLOG")
 (:integer +log-lpr+ "LOG_LPR")
 (:integer +log-news+ "LOG_NEWS")
 (:integer +log-uucp+ "LOG_UUCP")
 (:integer +log-cron+ "LOG_CRON")
 (:integer +log-authpriv+ "LOG_AUTHPRIV")
 (:integer +log-ftp+ "LOG_FTP")
 (:integer +log-local0+ "LOG_LOCAL0")
 (:integer +log-local1+ "LOG_LOCAL1")
 (:integer +log-local2+ "LOG_LOCAL2")
 (:integer +log-local3+ "LOG_LOCAL3")
 (:integer +log-local4+ "LOG_LOCAL4")
 (:integer +log-local5+ "LOG_LOCAL5")
 (:integer +log-local6+ "LOG_LOCAL6")
 (:integer +log-local7+ "LOG_LOCAL7")
 (:integer +log-nfacilities+ "LOG_NFACILITIES")
 (:integer +log-facmask+ "LOG_FACMASK")
 (:integer +log-pid+ "LOG_PID")
 (:integer +log-cons+ "LOG_CONS")
 (:integer +log-odelay+ "LOG_ODELAY")
 (:integer +log-ndelay+ "LOG_NDELAY")
 (:integer +log-nowait+ "LOG_NOWAIT")
 (:integer +log-perror+ "LOG_PERROR"))
