("signal.h" "errno.h" "sys/stat.h" "sys/syscall.h"
 "sys/epoll.h" "sys/syslog.h" "sys/socket.h" "sys/un.h"
 "net/if.h" "netinet/in.h" "netinet/tcp.h" "netinet/ip.h" 
 "linux/icmp.h" "linux/errqueue.h" "linux/netlink.h" "arpa/inet.h"
 "fcntl.h" "netdb.h" "sys/resource.h" "sys/poll.h")

(;; signals
 ;; (:integer sig-ign "SIG_IGN") 1
 ;; (:long sig-dfl "SIG_DFL") 0
 (:integer sa-nocldstop "SA_NOCLDSTOP")
 (:integer sa-nocldwait "SA_NOCLDWAIT")
 (:integer sa-nodefer "SA_NODEFER")
 (:integer sa-onstack "SA_ONSTACK")
 (:integer sa-resethand "SA_RESETHAND")
 (:integer sa-restart "SA_RESTART")
 (:integer sa-siginfo "SA_SIGINFO")
 ;; fcntl
 (:integer o-cloexec "O_CLOEXEC")
 ;; stat
 (:integer s-irwxu "S_IRWXU")
 (:integer s-irusr "S_IRUSR")
 (:integer s-iwusr "S_IWUSR")
 (:integer s-ixusr "S_IXUSR")
 (:integer s-ififo "S_IFIFO")
 (:integer s-ifchr "S_IFCHR")
 (:integer s-ifblk "S_IFBLK")
 (:integer s-iread "S_IREAD")
 (:integer s-iwrite "S_IWRITE")
 (:integer s-iexec "S_IEXEC")
 (:integer s-irwxg "S_IRWXG")
 (:integer s-irgrp "S_IRGRP")
 (:integer s-iwgrp "S_IWGRP")
 (:integer s-ixgrp "S_IXGRP")
 (:integer s-irwxo "S_IRWXO")
 (:integer s-iroth "S_IROTH")
 (:integer s-iwoth "S_IWOTH")
 (:integer s-ixoth "S_IXOTH")
 (:integer s-isuid "S_ISUID")
 (:integer s-isgid "S_ISGID")
 (:integer s-isvtx "S_ISVTX")
 (:integer s-ifsock "S_IFSOCK")
 ;; errno
 (:integer ecanceled "ECANCELED")
 (:integer enotsup "ENOTSUP")
 ;; (:integer ebug "EBUG")
 ;; syscalls
 (:integer +sys-gettid+ "SYS_gettid")
 (:integer +sys-bpf+ "SYS_bpf")
 ;; epoll
 (:integer epoll-cloexec "EPOLL_CLOEXEC")
 (:integer epoll-ctl-add "EPOLL_CTL_ADD")
 (:integer epoll-ctl-del "EPOLL_CTL_DEL")
 (:integer epoll-ctl-mod "EPOLL_CTL_MOD")
 (:integer epollin "EPOLLIN")
 (:integer epollrdnorm "EPOLLRDNORM")
 (:integer epollrdband "EPOLLRDBAND")
 (:integer epollpri "EPOLLPRI")
 (:integer epollout "EPOLLOUT")
 (:integer epollwrnorm "EPOLLWRNORM")
 (:integer epollwrband "EPOLLWRBAND")
 (:integer epollerr "EPOLLERR")
 (:integer epollhup "EPOLLHUP")
 (:integer epollmsg "EPOLLMSG")
 (:integer epolloneshot "EPOLLONESHOT")
 (:integer epollet "EPOLLET")
 ;; syslog
 (:integer +log-emerg+ "LOG_EMERG")
 (:integer +log-alert+ "LOG_ALERT")
 (:integer +log-crit+ "LOG_CRIT")
 (:integer +log-err+ "LOG_ERR")
 (:integer +log-warning+ "LOG_WARNING")
 (:integer +log-notice+ "LOG_NOTICE")
 (:integer +log-info+ "LOG_INFO")
 (:integer +log-debug+ "LOG_DEBUG")
 (:integer +log-primask+ "LOG_PRIMASK")
 (:integer +log-kern+ "LOG_KERN")
 (:integer +log-user+ "LOG_USER")
 (:integer +log-mail+ "LOG_MAIL")
 (:integer +log-daemon+ "LOG_DAEMON")
 (:integer +log-auth+ "LOG_AUTH")
 (:integer +log-syslog+ "LOG_SYSLOG")
 (:integer +log-lpr+ "LOG_LPR")
 (:integer +log-news+ "LOG_NEWS")
 (:integer +log-uucp+ "LOG_UUCP")
 (:integer +log-cron+ "LOG_CRON")
 (:integer +log-authpriv+ "LOG_AUTHPRIV")
 (:integer +log-ftp+ "LOG_FTP")
 (:integer +log-local0+ "LOG_LOCAL0")
 (:integer +log-local1+ "LOG_LOCAL1")
 (:integer +log-local2+ "LOG_LOCAL2")
 (:integer +log-local3+ "LOG_LOCAL3")
 (:integer +log-local4+ "LOG_LOCAL4")
 (:integer +log-local5+ "LOG_LOCAL5")
 (:integer +log-local6+ "LOG_LOCAL6")
 (:integer +log-local7+ "LOG_LOCAL7")
 (:integer +log-nfacilities+ "LOG_NFACILITIES")
 (:integer +log-facmask+ "LOG_FACMASK")
 (:integer +log-pid+ "LOG_PID")
 (:integer +log-cons+ "LOG_CONS")
 (:integer +log-odelay+ "LOG_ODELAY")
 (:integer +log-ndelay+ "LOG_NDELAY")
 (:integer +log-nowait+ "LOG_NOWAIT")
 (:integer +log-perror+ "LOG_PERROR")
 ;; resource
 (:integer prio-process "PRIO_PROCESS")
 (:integer prio-pgrp "PRIO_PGRP")
 (:integer prio-user "PRIO_USER")
 (:integer rlim-infinity "RLIM_INFINITY")
 (:integer rusage-self "RUSAGE_SELF")
 (:integer rusage-children "RUSAGE_CHILDREN")
 (:integer rlimit-as "RLIMIT_AS")
 (:integer rlimit-core "RLIMIT_CORE")
 (:integer rlimit-cpu "RLIMIT_CPU")
 (:integer rlimit-data "RLIMIT_DATA")
 (:integer rlimit-fsize "RLIMIT_FSIZE")
 (:integer rlimit-memlock "RLIMIT_MEMLOCK")
 (:integer rlimit-nofile "RLIMIT_NOFILE")
 (:integer rlimit-nproc "RLIMIT_NPROC")
 (:integer rlimit-rss "RLIMIT_RSS")
 (:integer rlimit-stack "RLIMIT_STACK")
 (:integer rlim-saved-max "RLIM_SAVED_MAX")
 (:integer rlim-saved-cur "RLIM_SAVED_CUR")
 (:integer rlimit-locks "RLIMIT_LOCKS")
 (:integer rlimit-msgqueue "RLIMIT_MSGQUEUE")
 (:integer rlimit-nlimits "RLIMIT_NLIMITS")
 (:integer rlimit-nice "RLIMIT_NICE")
 (:integer rlimit-rtprio "RLIMIT_RTPRIO")
 (:integer rlimit-sigpending "RLIMIT_SIGPENDING")
 ;; socket
 (:integer ipproto_icmpv6 "IPPROTO_ICMPV6") ; same convention as sockint
 (:integer ipproto_sctp "IPPROTO_SCTP")
 (:integer somaxconn "SOMAXCONN")
 (:integer sol-tcp "SOL_TCP")
 (:integer sol-ip "SOL_IP")
 (:integer sol-raw "SOL_RAW")
 (:integer so-acceptconn "SO_ACCEPTCONN")
 (:integer so-peercred "SO_PEERCRED")
 (:integer so-timestamp "SO_TIMESTAMP")
 ;; tcp
 (:integer tcp-cork "TCP_CORK")
 (:integer tcp-defer-accept "TCP_DEFER_ACCEPT")
 (:integer tcp-info "TCP_INFO")
 (:integer tcp-keepcnt "TCP_KEEPCNT")
 (:integer tcp-keepidle "TCP_KEEPIDLE")
 (:integer tcp-keepintvl "TCP_KEEPINTVL")
 (:integer tcp-linger2 "TCP_LINGER2")
 (:integer tcp-maxseg "TCP_MAXSEG")
 (:integer tcp-nodelay "TCP_NODELAY")
 (:integer tcp-quickack "TCP_QUICKACK")
 (:integer tcp-syncnt "TCP_SYNCNT")
 (:integer tcp-window-clamp "TCP_WINDOW_CLAMP")
 ;; ip
 (:integer ip-hdrincl "IP_HDRINCL")
 (:integer ip-recverr "IP_RECVERR")
 ;; raw
 (:integer icmp-filter "ICMP_FILTER")
 (:integer icmp-echo-request "ICMP_ECHO")
 (:integer icmp-echo-reply "ICMP_ECHOREPLY")
 (:integer icmp-dest-unreach "ICMP_DEST_UNREACH")
 (:integer icmp-source-quench "ICMP_SOURCE_QUENCH")
 (:integer icmp-redirect "ICMP_REDIRECT")
 (:integer icmp-time-exceeded "ICMP_TIME_EXCEEDED")
 (:integer icmp-parameter-prob "ICMP_PARAMETERPROB")
 (:integer icmp-timestamp-request "ICMP_TIMESTAMP")
 (:integer icmp-timestamp-reply "ICMP_TIMESTAMPREPLY")
 (:integer icmp-info-request "ICMP_INFO_REQUEST")
 (:integer icmp-info-reply "ICMP_INFO_REPLY")
 (:integer icmp-address-request "ICMP_ADDRESS")
 (:integer icmp-address-reply "ICMP_ADDRESSREPLY")
 (:integer icmp-net-unreach "ICMP_NET_UNREACH")
 (:integer icmp-host-unreach "ICMP_HOST_UNREACH")
 (:integer icmp-prot-unreach "ICMP_PROT_UNREACH")
 (:integer icmp-port-unreach "ICMP_PORT_UNREACH")
 (:integer icmp-frag-needed "ICMP_FRAG_NEEDED")
 (:integer icmp-sr-failed "ICMP_SR_FAILED")
 (:integer icmp-net-unknown "ICMP_NET_UNKNOWN")
 (:integer icmp-host-unknown "ICMP_HOST_UNKNOWN")
 (:integer icmp-host-isolated "ICMP_HOST_ISOLATED")
 (:integer icmp-net-ano "ICMP_NET_ANO")
 (:integer icmp-host-ano "ICMP_HOST_ANO")
 (:integer icmp-net-unr-tos "ICMP_NET_UNR_TOS")
 (:integer icmp-host-unr-tos "ICMP_HOST_UNR_TOS")
 (:integer icmp-pkt-filtered "ICMP_PKT_FILTERED")
 (:integer icmp-prec-violation "ICMP_PREC_VIOLATION")
 (:integer icmp-prec-cutoff "ICMP_PREC_CUTOFF")
 (:integer icmp-redir-net "ICMP_REDIR_NET")
 (:integer icmp-redir-host "ICMP_REDIR_HOST")
 (:integer icmp-redir-nettos "ICMP_REDIR_NETTOS")
 (:integer icmp-redir-hosttos "ICMP_REDIR_HOSTTOS")
 (:integer icmp-exc-ttl "ICMP_EXC_TTL")
 (:integer icmp-exc-fragtime "ICMP_EXC_FRAGTIME")
 ;; shutdown
 (:integer shut-rd "SHUT_RD")
 (:integer shut-wr "SHUT_WR")
 (:integer shut-rdwr "SHUT_RDWR")
 ;;recv/sendmsg
 (:integer msg-errqueue "MSG_ERRQUEUE")
 (:integer msg-proxy "MSG_PROXY")
 (:integer msg-fin "MSG_FIN")
 (:integer msg-syn "MSG_SYN")
 ;; (:integer msg-eof "MSG_EOF")
 ;; (:integer msg-nbio "MSG_NBIO")
 ;; (:integer msg-compat "MSG_COMPAT")
 (:integer msg-ctrunc "MSG_CTRUNC")
 ;; inet
 (:integer ipv6-join-group "IPV6_JOIN_GROUP")
 (:integer ipv6-leave-group "IPV6_LEAVE_GROUP")
 (:integer ipv6-multicast-hops "IPV6_MULTICAST_HOPS")
 (:integer ipv6-multicast-if "IPV6_MULTICAST_IF")
 (:integer ipv6-multicast-loop "IPV6_MULTICAST_LOOP")
 (:integer ipv6-unicast-hops "IPV6_UNICAST_HOPS")
 (:integer ipv6-v6only "IPV6_V6ONLY")
 ;; net/if
 (:integer if-namesize "IF_NAMESIZE")
 (:integer if-namsiz "IFNAMSIZ")
 ;; sys/poll
 (:integer epollrdhup "EPOLLRDHUP") ;; can't grovel for pollrdhup, epollrdhup is the same afaik
 (:integer pollpri "POLLPRI")
 (:integer pollrdnorm "POLLRDNORM")
 (:integer pollrdband "POLLRDBAND")
 (:integer pollwrnorm "POLLWRNORM")
 (:integer pollwrband "POLLWRBAND"))
