("sys/syscall.h" "sys/syslog.h" "signal.h" "errno.h")

(;; syscalls
 (:integer +sys-gettid+ "SYS_gettid")
 (:integer +sys-bpf+ "SYS_bpf")
 ;; syslog
 (:integer +log-emerg+ "LOG_EMERG")
 (:integer +log-alert+ "LOG_ALERT")
 (:integer +log-crit+ "LOG_CRIT")
 (:integer +log-err+ "LOG_ERR")
 (:integer +log-warning+ "LOG_WARNING")
 (:integer +log-notice+ "LOG_NOTICE")
 (:integer +log-info+ "LOG_INFO")
 (:integer +log-debug+ "LOG_DEBUG")
 (:integer +log-primask+ "LOG_PRIMASK")
 (:integer +log-kern+ "LOG_KERN")
 (:integer +log-user+ "LOG_USER")
 (:integer +log-mail+ "LOG_MAIL")
 (:integer +log-daemon+ "LOG_DAEMON")
 (:integer +log-auth+ "LOG_AUTH")
 (:integer +log-syslog+ "LOG_SYSLOG")
 (:integer +log-lpr+ "LOG_LPR")
 (:integer +log-news+ "LOG_NEWS")
 (:integer +log-uucp+ "LOG_UUCP")
 (:integer +log-cron+ "LOG_CRON")
 (:integer +log-authpriv+ "LOG_AUTHPRIV")
 (:integer +log-ftp+ "LOG_FTP")
 (:integer +log-local0+ "LOG_LOCAL0")
 (:integer +log-local1+ "LOG_LOCAL1")
 (:integer +log-local2+ "LOG_LOCAL2")
 (:integer +log-local3+ "LOG_LOCAL3")
 (:integer +log-local4+ "LOG_LOCAL4")
 (:integer +log-local5+ "LOG_LOCAL5")
 (:integer +log-local6+ "LOG_LOCAL6")
 (:integer +log-local7+ "LOG_LOCAL7")
 (:integer +log-nfacilities+ "LOG_NFACILITIES")
 (:integer +log-facmask+ "LOG_FACMASK")
 (:integer +log-pid+ "LOG_PID")
 (:integer +log-cons+ "LOG_CONS")
 (:integer +log-odelay+ "LOG_ODELAY")
 (:integer +log-ndelay+ "LOG_NDELAY")
 (:integer +log-nowait+ "LOG_NOWAIT")
 (:integer +log-perror+ "LOG_PERROR"))
